/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Timer/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Timer {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace SetTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SetTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SetTime
namespace TimeRemaining{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TimeRemaining::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TimeRemaining
namespace TimerState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TimerState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TimerState

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    SetTime::kMetadataEntry,
    TimeRemaining::kMetadataEntry,
    TimerState::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SetTimer {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetTimer::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SetTimer
namespace ResetTimer {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ResetTimer::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace ResetTimer
namespace AddTime {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AddTime::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace AddTime
namespace ReduceTime {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ReduceTime::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace ReduceTime

} // namespace Commands
} // namespace Timer
} // namespace Clusters
} // namespace app
} // namespace chip
