/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/TemperatureControl/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace TemperatureControl {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace TemperatureSetpoint{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TemperatureSetpoint::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TemperatureSetpoint
namespace MinTemperature{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MinTemperature::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MinTemperature
namespace MaxTemperature{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxTemperature::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxTemperature
namespace Step{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Step::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Step
namespace SelectedTemperatureLevel{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SelectedTemperatureLevel::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SelectedTemperatureLevel
namespace SupportedTemperatureLevels{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SupportedTemperatureLevels::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SupportedTemperatureLevels

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {
namespace SetTemperature {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetTemperature::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SetTemperature

} // namespace Commands
} // namespace TemperatureControl
} // namespace Clusters
} // namespace app
} // namespace chip
