/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/EthernetNetworkDiagnostics/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace EthernetNetworkDiagnostics {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace PHYRate{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PHYRate::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PHYRate
namespace FullDuplex{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    FullDuplex::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace FullDuplex
namespace PacketRxCount{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PacketRxCount::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PacketRxCount
namespace PacketTxCount{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PacketTxCount::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PacketTxCount
namespace TxErrCount{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TxErrCount::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TxErrCount
namespace CollisionCount{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CollisionCount::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CollisionCount
namespace OverrunCount{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OverrunCount::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OverrunCount
namespace CarrierDetect{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CarrierDetect::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CarrierDetect
namespace TimeSinceReset{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TimeSinceReset::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TimeSinceReset

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {
namespace ResetCounts {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ResetCounts::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace ResetCounts

} // namespace Commands
} // namespace EthernetNetworkDiagnostics
} // namespace Clusters
} // namespace app
} // namespace chip
