/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Actions {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 12;


namespace InstantAction {
inline constexpr CommandId Id = 0x00000000;
} // namespace InstantAction

namespace InstantActionWithTransition {
inline constexpr CommandId Id = 0x00000001;
} // namespace InstantActionWithTransition

namespace StartAction {
inline constexpr CommandId Id = 0x00000002;
} // namespace StartAction

namespace StartActionWithDuration {
inline constexpr CommandId Id = 0x00000003;
} // namespace StartActionWithDuration

namespace StopAction {
inline constexpr CommandId Id = 0x00000004;
} // namespace StopAction

namespace PauseAction {
inline constexpr CommandId Id = 0x00000005;
} // namespace PauseAction

namespace PauseActionWithDuration {
inline constexpr CommandId Id = 0x00000006;
} // namespace PauseActionWithDuration

namespace ResumeAction {
inline constexpr CommandId Id = 0x00000007;
} // namespace ResumeAction

namespace EnableAction {
inline constexpr CommandId Id = 0x00000008;
} // namespace EnableAction

namespace EnableActionWithDuration {
inline constexpr CommandId Id = 0x00000009;
} // namespace EnableActionWithDuration

namespace DisableAction {
inline constexpr CommandId Id = 0x0000000A;
} // namespace DisableAction

namespace DisableActionWithDuration {
inline constexpr CommandId Id = 0x0000000B;
} // namespace DisableActionWithDuration

} // Commands
} // Actions
} // Clusters
} // app
} // chip
