/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ServiceArea/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ServiceArea {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace SupportedAreas{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SupportedAreas::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SupportedAreas
namespace SupportedMaps{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SupportedMaps::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SupportedMaps
namespace SelectedAreas{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SelectedAreas::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SelectedAreas
namespace CurrentArea{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentArea::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentArea
namespace EstimatedEndTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    EstimatedEndTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace EstimatedEndTime
namespace Progress{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Progress::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Progress

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    SupportedAreas::kMetadataEntry,
    SelectedAreas::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SelectAreas {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SelectAreas::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SelectAreas
namespace SkipArea {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SkipArea::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SkipArea

} // namespace Commands
} // namespace ServiceArea
} // namespace Clusters
} // namespace app
} // namespace chip
