/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Channel/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Channel {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace ChannelList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ChannelList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ChannelList
namespace Lineup{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Lineup::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Lineup
namespace CurrentChannel{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentChannel::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentChannel

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {
namespace ChangeChannel {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ChangeChannel::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace ChangeChannel
namespace ChangeChannelByNumber {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ChangeChannelByNumber::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace ChangeChannelByNumber
namespace SkipChannel {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SkipChannel::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SkipChannel
namespace GetProgramGuide {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GetProgramGuide::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace GetProgramGuide
namespace RecordProgram {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RecordProgram::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace RecordProgram
namespace CancelRecordProgram {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    CancelRecordProgram::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace CancelRecordProgram

} // namespace Commands
} // namespace Channel
} // namespace Clusters
} // namespace app
} // namespace chip
