/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Chime/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Chime {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace InstalledChimeSounds{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    InstalledChimeSounds::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace InstalledChimeSounds
namespace SelectedChime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SelectedChime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace SelectedChime
namespace Enabled{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Enabled::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace Enabled

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    InstalledChimeSounds::kMetadataEntry,
    SelectedChime::kMetadataEntry,
    Enabled::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace PlayChimeSound {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    PlayChimeSound::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace PlayChimeSound

} // namespace Commands
} // namespace Chime
} // namespace Clusters
} // namespace app
} // namespace chip
