/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace MediaPlayback {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 14;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 1;

namespace Play {
inline constexpr CommandId Id = 0x00000000;
} // namespace Play

namespace Pause {
inline constexpr CommandId Id = 0x00000001;
} // namespace Pause

namespace Stop {
inline constexpr CommandId Id = 0x00000002;
} // namespace Stop

namespace StartOver {
inline constexpr CommandId Id = 0x00000003;
} // namespace StartOver

namespace Previous {
inline constexpr CommandId Id = 0x00000004;
} // namespace Previous

namespace Next {
inline constexpr CommandId Id = 0x00000005;
} // namespace Next

namespace Rewind {
inline constexpr CommandId Id = 0x00000006;
} // namespace Rewind

namespace FastForward {
inline constexpr CommandId Id = 0x00000007;
} // namespace FastForward

namespace SkipForward {
inline constexpr CommandId Id = 0x00000008;
} // namespace SkipForward

namespace SkipBackward {
inline constexpr CommandId Id = 0x00000009;
} // namespace SkipBackward

namespace PlaybackResponse {
inline constexpr CommandId Id = 0x0000000A;
} // namespace PlaybackResponse

namespace Seek {
inline constexpr CommandId Id = 0x0000000B;
} // namespace Seek

namespace ActivateAudioTrack {
inline constexpr CommandId Id = 0x0000000C;
} // namespace ActivateAudioTrack

namespace ActivateTextTrack {
inline constexpr CommandId Id = 0x0000000D;
} // namespace ActivateTextTrack

namespace DeactivateTextTrack {
inline constexpr CommandId Id = 0x0000000E;
} // namespace DeactivateTextTrack

} // Commands
} // MediaPlayback
} // Clusters
} // app
} // chip
