/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/EcosystemInformation/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace EcosystemInformation {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace DeviceDirectory{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DeviceDirectory::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kManage,
    std::nullopt
);
} // namespace DeviceDirectory
namespace LocationDirectory{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    LocationDirectory::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kManage,
    std::nullopt
);
} // namespace LocationDirectory

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    DeviceDirectory::kMetadataEntry,
    LocationDirectory::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {

} // namespace Commands
} // namespace EcosystemInformation
} // namespace Clusters
} // namespace app
} // namespace chip
