/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ValveConfigurationAndControl/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ValveConfigurationAndControl {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace OpenDuration{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OpenDuration::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OpenDuration
namespace DefaultOpenDuration{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DefaultOpenDuration::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace DefaultOpenDuration
namespace AutoCloseTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AutoCloseTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AutoCloseTime
namespace RemainingDuration{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    RemainingDuration::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace RemainingDuration
namespace CurrentState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentState
namespace TargetState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TargetState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TargetState
namespace CurrentLevel{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentLevel::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentLevel
namespace TargetLevel{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TargetLevel::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TargetLevel
namespace DefaultOpenLevel{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DefaultOpenLevel::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace DefaultOpenLevel
namespace ValveFault{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ValveFault::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ValveFault
namespace LevelStep{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    LevelStep::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace LevelStep

constexpr std::array<DataModel::AttributeEntry, 5> kMandatoryMetadata = {
    OpenDuration::kMetadataEntry,
    DefaultOpenDuration::kMetadataEntry,
    RemainingDuration::kMetadataEntry,
    CurrentState::kMetadataEntry,
    TargetState::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace Open {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Open::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Open
namespace Close {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Close::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Close

} // namespace Commands
} // namespace ValveConfigurationAndControl
} // namespace Clusters
} // namespace app
} // namespace chip
