/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Groupcast/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Groupcast {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace Membership{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Membership::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Membership
namespace MaxMembershipCount{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxMembershipCount::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxMembershipCount

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    Membership::kMetadataEntry,
    MaxMembershipCount::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace JoinGroup {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    JoinGroup::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace JoinGroup
namespace LeaveGroup {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    LeaveGroup::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace LeaveGroup
namespace UpdateGroupKey {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    UpdateGroupKey::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace UpdateGroupKey
namespace ExpireGracePeriod {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ExpireGracePeriod::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace ExpireGracePeriod
namespace ConfigureAuxiliaryACL {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ConfigureAuxiliaryACL::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kAdminister
);
} // namespace ConfigureAuxiliaryACL

} // namespace Commands
} // namespace Groupcast
} // namespace Clusters
} // namespace app
} // namespace chip
