/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/FaultInjection/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FaultInjection {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {
namespace FailAtFault {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    FailAtFault::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace FailAtFault
namespace FailRandomlyAtFault {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    FailRandomlyAtFault::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace FailRandomlyAtFault

} // namespace Commands
} // namespace FaultInjection
} // namespace Clusters
} // namespace app
} // namespace chip
