/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Thermostat {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 9;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 3;

namespace SetpointRaiseLower {
inline constexpr CommandId Id = 0x00000000;
} // namespace SetpointRaiseLower

namespace GetWeeklyScheduleResponse {
inline constexpr CommandId Id = 0x00000000;
} // namespace GetWeeklyScheduleResponse

namespace SetWeeklySchedule {
inline constexpr CommandId Id = 0x00000001;
} // namespace SetWeeklySchedule

namespace GetWeeklySchedule {
inline constexpr CommandId Id = 0x00000002;
} // namespace GetWeeklySchedule

namespace AddThermostatSuggestionResponse {
inline constexpr CommandId Id = 0x00000002;
} // namespace AddThermostatSuggestionResponse

namespace ClearWeeklySchedule {
inline constexpr CommandId Id = 0x00000003;
} // namespace ClearWeeklySchedule

namespace SetActiveScheduleRequest {
inline constexpr CommandId Id = 0x00000005;
} // namespace SetActiveScheduleRequest

namespace SetActivePresetRequest {
inline constexpr CommandId Id = 0x00000006;
} // namespace SetActivePresetRequest

namespace AddThermostatSuggestion {
inline constexpr CommandId Id = 0x00000007;
} // namespace AddThermostatSuggestion

namespace RemoveThermostatSuggestion {
inline constexpr CommandId Id = 0x00000008;
} // namespace RemoveThermostatSuggestion

namespace AtomicResponse {
inline constexpr CommandId Id = 0x000000FD;
} // namespace AtomicResponse

namespace AtomicRequest {
inline constexpr CommandId Id = 0x000000FE;
} // namespace AtomicRequest

} // Commands
} // Thermostat
} // Clusters
} // app
} // chip
