/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Thermostat {
namespace Events {
namespace SystemModeChange {
inline constexpr EventId Id = 0x00000000;
} // namespace SystemModeChange

namespace LocalTemperatureChange {
inline constexpr EventId Id = 0x00000001;
} // namespace LocalTemperatureChange

namespace OccupancyChange {
inline constexpr EventId Id = 0x00000002;
} // namespace OccupancyChange

namespace SetpointChange {
inline constexpr EventId Id = 0x00000003;
} // namespace SetpointChange

namespace RunningStateChange {
inline constexpr EventId Id = 0x00000004;
} // namespace RunningStateChange

namespace RunningModeChange {
inline constexpr EventId Id = 0x00000005;
} // namespace RunningModeChange

namespace ActiveScheduleChange {
inline constexpr EventId Id = 0x00000006;
} // namespace ActiveScheduleChange

namespace ActivePresetChange {
inline constexpr EventId Id = 0x00000007;
} // namespace ActivePresetChange

} // Commands
} // Thermostat
} // Events
} // app
} // chip
