"""Read and write filtered SLT slconf files for Matter apps."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from .filters import (
    detect_app_stack_type,
    filter_slc_sdk_paths,
    parse_slconf_path_comment_package,
    path_is_slc_extension_root,
)

USER_SLCONF = """# Shipped with matter_app. Regenerated by matter-app-slconf after slt install.
include = [
  "autogen/slc-sdk.slconf"
]
"""


def parse_pkg_slconf(slconf_path: Path) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    current: Optional[str] = None

    if not slconf_path.is_file():
        return sections

    with slconf_path.open("r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.rstrip("\n")
            stripped = line.strip()
            if stripped.startswith("[") and stripped.endswith("]"):
                current = stripped[1:-1]
                sections.setdefault(current, [])
                continue
            if current is not None:
                sections[current].append(line)

    return sections


def parse_pkg_slconf_sdk_paths(slconf_path: Path) -> list[str]:
    if not slconf_path.is_file():
        return []

    paths: list[str] = []
    path_lines: dict[str, str] = {}
    in_slc = False
    in_list = False

    with slconf_path.open("r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if line == "[slc]":
                in_slc = True
                continue
            if in_slc and line.startswith("[") and line != "[slc]":
                break
            if not in_slc:
                continue
            if line.startswith("sdk-package-path"):
                in_list = True
                continue
            if not in_list:
                continue
            if line == "]":
                break
            match = re.match(r'^"([^"]+)"', line)
            if match:
                entry = match.group(1)
                paths.append(entry)
                path_lines[entry] = raw_line.rstrip("\n")

    parse_pkg_slconf_sdk_paths._path_lines = path_lines  # type: ignore[attr-defined]
    return paths


def slconf_sdk_path_lines(slconf_path: Path) -> dict[str, str]:
    parse_pkg_slconf_sdk_paths(slconf_path)
    return getattr(parse_pkg_slconf_sdk_paths, "_path_lines", {})


def _find_path_for_package(
    raw_paths: list[str],
    path_lines: dict[str, str],
    package_name: str,
) -> Optional[str]:
    for path in raw_paths:
        line = path_lines.get(path, "")
        if parse_slconf_path_comment_package(line) == package_name:
            if path_is_slc_extension_root(path):
                return path
    return None


def _order_sdk_paths(
    filtered_paths: list[str],
    *,
    base_sdk_path: Optional[str],
    matter_path: Optional[str],
) -> list[str]:
    ordered = [p for p in filtered_paths if p not in {base_sdk_path, matter_path}]
    if base_sdk_path:
        ordered.insert(0, base_sdk_path)
    if matter_path:
        insert_at = 1 if ordered and base_sdk_path and ordered[0] == base_sdk_path else 0
        ordered.insert(insert_at, matter_path)
    return ordered


def write_filtered_app_slconf(
    app_dir: Path,
    *,
    slcp_name: str = "",
    source_slconf: Optional[Path] = None,
) -> Path:
    app_dir = app_dir.resolve()
    autogen = app_dir / "autogen"
    source = source_slconf or (autogen / "pkg.slconf")
    if not source.is_file():
        raise FileNotFoundError(f"SLT pkg.slconf not found: {source}")

    app_type = detect_app_stack_type(app_dir, slcp_name=slcp_name)
    sections = parse_pkg_slconf(source)
    raw_paths = parse_pkg_slconf_sdk_paths(source)
    path_lines = slconf_sdk_path_lines(source)
    filtered_paths = filter_slc_sdk_paths(
        raw_paths,
        app_type=app_type,
        raw_slconf_lines=path_lines,
    )
    base_sdk_path = _find_path_for_package(raw_paths, path_lines, "base_sdk")
    matter_path = _find_path_for_package(raw_paths, path_lines, "matter")
    filtered_paths = _order_sdk_paths(
        filtered_paths,
        base_sdk_path=base_sdk_path,
        matter_path=matter_path,
    )

    if not filtered_paths:
        raise RuntimeError(
            f"No valid sdk-package-path roots for {app_dir} (app_type={app_type})"
        )

    out_path = autogen / "slc-sdk.slconf"
    autogen.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Generated by matter-app-slconf. Filtered sdk-package-path for slc generate.",
        "",
    ]

    if "core" in sections:
        lines.append("[core]")
        lines.extend(sections["core"])
        lines.append("")

    lines.append("[slc]")
    lines.append("sdk-package-path = [")
    for path in filtered_paths:
        comment = ""
        if path in path_lines:
            comment_match = re.search(r"#.*", path_lines[path])
            if comment_match:
                comment = f"    {comment_match.group(0)}"
        lines.append(f'  "{path}",{comment}')
    lines.append("]")
    lines.append("")

    if "toolchain" in sections:
        lines.append("[toolchain]")
        lines.extend(sections["toolchain"])
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    (app_dir / "user.slconf").write_text(USER_SLCONF, encoding="utf-8")
    return out_path
