/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/BooleanStateConfiguration/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace BooleanStateConfiguration {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace CurrentSensitivityLevel{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentSensitivityLevel::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace CurrentSensitivityLevel
namespace SupportedSensitivityLevels{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SupportedSensitivityLevels::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SupportedSensitivityLevels
namespace DefaultSensitivityLevel{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DefaultSensitivityLevel::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace DefaultSensitivityLevel
namespace AlarmsActive{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AlarmsActive::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AlarmsActive
namespace AlarmsSuppressed{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AlarmsSuppressed::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AlarmsSuppressed
namespace AlarmsEnabled{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AlarmsEnabled::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AlarmsEnabled
namespace AlarmsSupported{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AlarmsSupported::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AlarmsSupported
namespace SensorFault{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SensorFault::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SensorFault

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {
namespace SuppressAlarm {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SuppressAlarm::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SuppressAlarm
namespace EnableDisableAlarm {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    EnableDisableAlarm::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace EnableDisableAlarm

} // namespace Commands
} // namespace BooleanStateConfiguration
} // namespace Clusters
} // namespace app
} // namespace chip
