/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ClosureControl/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ClosureControl {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace CountdownTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CountdownTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CountdownTime
namespace MainState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MainState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MainState
namespace CurrentErrorList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentErrorList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentErrorList
namespace OverallCurrentState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OverallCurrentState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OverallCurrentState
namespace OverallTargetState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OverallTargetState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OverallTargetState
namespace LatchControlModes{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    LatchControlModes::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace LatchControlModes

constexpr std::array<DataModel::AttributeEntry, 4> kMandatoryMetadata = {
    MainState::kMetadataEntry,
    CurrentErrorList::kMetadataEntry,
    OverallCurrentState::kMetadataEntry,
    OverallTargetState::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace Stop {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Stop::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Stop
namespace MoveTo {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    MoveTo::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kOperate
);
} // namespace MoveTo
namespace Calibrate {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Calibrate::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kManage
);
} // namespace Calibrate

} // namespace Commands
} // namespace ClosureControl
} // namespace Clusters
} // namespace app
} // namespace chip
