/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Messages/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Messages {

inline constexpr uint32_t kRevision = 3;

namespace Attributes {
namespace Messages{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Messages::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Messages
namespace ActiveMessageIDs{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ActiveMessageIDs::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ActiveMessageIDs

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    Messages::kMetadataEntry,
    ActiveMessageIDs::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace PresentMessagesRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    PresentMessagesRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace PresentMessagesRequest
namespace CancelMessagesRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    CancelMessagesRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace CancelMessagesRequest

} // namespace Commands
} // namespace Messages
} // namespace Clusters
} // namespace app
} // namespace chip
