/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ClosureDimension/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ClosureDimension {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace CurrentState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentState
namespace TargetState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TargetState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TargetState
namespace Resolution{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Resolution::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Resolution
namespace StepValue{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    StepValue::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace StepValue
namespace Unit{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Unit::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Unit
namespace UnitRange{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UnitRange::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace UnitRange
namespace LimitRange{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    LimitRange::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace LimitRange
namespace TranslationDirection{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TranslationDirection::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TranslationDirection
namespace RotationAxis{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    RotationAxis::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace RotationAxis
namespace Overflow{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Overflow::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Overflow
namespace ModulationType{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ModulationType::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ModulationType
namespace LatchControlModes{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    LatchControlModes::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace LatchControlModes

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    CurrentState::kMetadataEntry,
    TargetState::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SetTarget {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetTarget::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kOperate
);
} // namespace SetTarget
namespace Step {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Step::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kOperate
);
} // namespace Step

} // namespace Commands
} // namespace ClosureDimension
} // namespace Clusters
} // namespace app
} // namespace chip
