name: Install Tools
description: Install required tools and set environment variables.

runs:
  using: "composite"
  steps:
    - name: Install ZAP
      shell: bash
      run: |
        wget https://github.com/project-chip/zap/releases/download/v2025.05.22/zap-linux-x64.zip
        unzip zap-linux-x64.zip -d /opt/silabs/zap-linux-x64
        rm zap-linux-x64.zip

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "STUDIO_ADAPTER_PACK_PATH=/opt/silabs/zap-linux-x64" >> $GITHUB_ENV