name: Install Tools
description: Install required tools and set environment variables.

runs:
  using: "composite"
  steps:
    - name: Set CONAN_HOME
      shell: bash
      run: |
        echo "CONAN_HOME=~/.silabs/slt/installs/conan" >> $GITHUB_ENV

    - name: Install ZAP
      shell: bash
      run: |
        MAX_RETRIES=3
        RETRY_COUNT=0
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          ZAP_VERSION=$(python3 slc/script/get_zap_version.py --docker)
          if wget "https://github.com/project-chip/zap/releases/download/${ZAP_VERSION}/zap-linux-x64.zip"; then
            unzip zap-linux-x64.zip -d /tmp/zap-linux-x64
            rm zap-linux-x64.zip
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "Download failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
              sleep 5
            else
              echo "Failed to download ZAP after $MAX_RETRIES attempts"
              exit 1
            fi
          fi
        done
    
    - name: Setup SLT
      id: setup-action
      uses: SiliconLabsSoftware/action-setup-slt@main
    
    - name: Set Environment Variables
      shell: bash
      run: |
        echo "STUDIO_ADAPTER_PACK_PATH=/tmp/zap-linux-x64" >> $GITHUB_ENV
        echo "SLT_PATH=${{ steps.setup-action.outputs.slt-path }}" >> $GITHUB_ENV
        echo "/tmp/zap-linux-x64" >> $GITHUB_PATH
        echo "${{ steps.setup-action.outputs.slt-path }}" >> $GITHUB_PATH
    
    - name: Install slc-cli
      shell: bash
      run: |
        MAX_RETRIES=3
        RETRY_COUNT=0
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if slt install slc-cli; then
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "slc-cli installation failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
              sleep 5
            else
              echo "Failed to install slc-cli after $MAX_RETRIES attempts"
              exit 1
            fi
          fi
        done
    
    - name: Set Environment Variables
      shell: bash
      run: |
        SLC_CLI_PATH=$(slt where slc-cli)
        echo "SLC_CLI_PATH=$SLC_CLI_PATH" >> $GITHUB_ENV
        JAVA_HOME=$(slt where java21)
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "$SLC_CLI_PATH" >> $GITHUB_PATH
        if [ -n "$JAVA_HOME" ]; then
          echo "$JAVA_HOME/jre/bin" >> $GITHUB_PATH
        fi
    
    - name: Install commander
      shell: bash
      run: |
        MAX_RETRIES=3
        RETRY_COUNT=0
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if slt install commander; then
            COMMANDER_PATH=$(slt where commander)
            echo "COMMANDER_PATH=$COMMANDER_PATH" >> $GITHUB_ENV
            echo "$COMMANDER_PATH" >> $GITHUB_PATH
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "commander installation failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
              sleep 5
            else
              echo "Failed to install commander after $MAX_RETRIES attempts"
              exit 1
            fi
          fi
        done
    
    - name: install gcc-arm-none-eabi
      shell: bash
      run: |
        MAX_RETRIES=3
        RETRY_COUNT=0
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if slt install gcc-arm-none-eabi; then
            ARM_GCC_DIR=$(slt where gcc-arm-none-eabi)
            echo "ARM_GCC_DIR=$ARM_GCC_DIR" >> $GITHUB_ENV
            echo "$ARM_GCC_DIR/bin" >> $GITHUB_PATH
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "gcc-arm-none-eabi installation failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
              sleep 5
            else
              echo "Failed to install gcc-arm-none-eabi after $MAX_RETRIES attempts"
              exit 1
            fi
          fi
        done