/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ApplicationLauncher/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ApplicationLauncher {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace CatalogList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CatalogList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CatalogList
namespace CurrentApp{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentApp::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentApp

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {
namespace LaunchApp {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    LaunchApp::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace LaunchApp
namespace StopApp {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    StopApp::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace StopApp
namespace HideApp {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    HideApp::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace HideApp

} // namespace Commands
} // namespace ApplicationLauncher
} // namespace Clusters
} // namespace app
} // namespace chip
