/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ActivatedCarbonFilterMonitoring/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ActivatedCarbonFilterMonitoring {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace Condition{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Condition::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Condition
namespace DegradationDirection{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DegradationDirection::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace DegradationDirection
namespace ChangeIndication{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ChangeIndication::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ChangeIndication
namespace InPlaceIndicator{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    InPlaceIndicator::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace InPlaceIndicator
namespace LastChangedTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    LastChangedTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace LastChangedTime
namespace ReplacementProductList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ReplacementProductList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ReplacementProductList

constexpr std::array<DataModel::AttributeEntry, 1> kMandatoryMetadata = {
    ChangeIndication::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace ResetCondition {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ResetCondition::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace ResetCondition

} // namespace Commands
} // namespace ActivatedCarbonFilterMonitoring
} // namespace Clusters
} // namespace app
} // namespace chip
