/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/PushAvStreamTransport/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace PushAvStreamTransport {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace SupportedFormats{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SupportedFormats::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SupportedFormats
namespace CurrentConnections{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentConnections::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentConnections

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    SupportedFormats::kMetadataEntry,
    CurrentConnections::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace AllocatePushTransport {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AllocatePushTransport::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace AllocatePushTransport
namespace DeallocatePushTransport {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    DeallocatePushTransport::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace DeallocatePushTransport
namespace ModifyPushTransport {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ModifyPushTransport::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace ModifyPushTransport
namespace SetTransportStatus {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetTransportStatus::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace SetTransportStatus
namespace ManuallyTriggerTransport {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ManuallyTriggerTransport::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace ManuallyTriggerTransport
namespace FindTransport {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    FindTransport::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace FindTransport

} // namespace Commands
} // namespace PushAvStreamTransport
} // namespace Clusters
} // namespace app
} // namespace chip
