/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace JointFabricAdministrator {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 6;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 3;

namespace ICACCSRRequest {
inline constexpr CommandId Id = 0x00000000;
} // namespace ICACCSRRequest

namespace ICACCSRResponse {
inline constexpr CommandId Id = 0x00000001;
} // namespace ICACCSRResponse

namespace AddICAC {
inline constexpr CommandId Id = 0x00000002;
} // namespace AddICAC

namespace ICACResponse {
inline constexpr CommandId Id = 0x00000003;
} // namespace ICACResponse

namespace OpenJointCommissioningWindow {
inline constexpr CommandId Id = 0x00000004;
} // namespace OpenJointCommissioningWindow

namespace TransferAnchorRequest {
inline constexpr CommandId Id = 0x00000005;
} // namespace TransferAnchorRequest

namespace TransferAnchorResponse {
inline constexpr CommandId Id = 0x00000006;
} // namespace TransferAnchorResponse

namespace TransferAnchorComplete {
inline constexpr CommandId Id = 0x00000007;
} // namespace TransferAnchorComplete

namespace AnnounceJointFabricAdministrator {
inline constexpr CommandId Id = 0x00000008;
} // namespace AnnounceJointFabricAdministrator

} // Commands
} // JointFabricAdministrator
} // Clusters
} // app
} // chip
