/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/JointFabricAdministrator/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace JointFabricAdministrator {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace AdministratorFabricIndex{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AdministratorFabricIndex::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kAdminister,
    std::nullopt
);
} // namespace AdministratorFabricIndex

constexpr std::array<DataModel::AttributeEntry, 1> kMandatoryMetadata = {
    AdministratorFabricIndex::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace ICACCSRRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ICACCSRRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace ICACCSRRequest
namespace AddICAC {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AddICAC::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace AddICAC
namespace OpenJointCommissioningWindow {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    OpenJointCommissioningWindow::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace OpenJointCommissioningWindow
namespace TransferAnchorRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    TransferAnchorRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace TransferAnchorRequest
namespace TransferAnchorComplete {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    TransferAnchorComplete::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace TransferAnchorComplete
namespace AnnounceJointFabricAdministrator {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AnnounceJointFabricAdministrator::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace AnnounceJointFabricAdministrator

} // namespace Commands
} // namespace JointFabricAdministrator
} // namespace Clusters
} // namespace app
} // namespace chip
