/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace SmokeCoAlarm {
namespace Events {
namespace SmokeAlarm {
inline constexpr EventId Id = 0x00000000;
} // namespace SmokeAlarm

namespace COAlarm {
inline constexpr EventId Id = 0x00000001;
} // namespace COAlarm

namespace LowBattery {
inline constexpr EventId Id = 0x00000002;
} // namespace LowBattery

namespace HardwareFault {
inline constexpr EventId Id = 0x00000003;
} // namespace HardwareFault

namespace EndOfService {
inline constexpr EventId Id = 0x00000004;
} // namespace EndOfService

namespace SelfTestComplete {
inline constexpr EventId Id = 0x00000005;
} // namespace SelfTestComplete

namespace AlarmMuted {
inline constexpr EventId Id = 0x00000006;
} // namespace AlarmMuted

namespace MuteEnded {
inline constexpr EventId Id = 0x00000007;
} // namespace MuteEnded

namespace InterconnectSmokeAlarm {
inline constexpr EventId Id = 0x00000008;
} // namespace InterconnectSmokeAlarm

namespace InterconnectCOAlarm {
inline constexpr EventId Id = 0x00000009;
} // namespace InterconnectCOAlarm

namespace AllClear {
inline constexpr EventId Id = 0x0000000A;
} // namespace AllClear

} // Commands
} // SmokeCoAlarm
} // Events
} // app
} // chip
