/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/SmokeCoAlarm/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace SmokeCoAlarm {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace ExpressedState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ExpressedState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ExpressedState
namespace SmokeState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SmokeState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SmokeState
namespace COState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    COState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace COState
namespace BatteryAlert{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    BatteryAlert::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace BatteryAlert
namespace DeviceMuted{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DeviceMuted::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace DeviceMuted
namespace TestInProgress{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TestInProgress::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TestInProgress
namespace HardwareFaultAlert{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    HardwareFaultAlert::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace HardwareFaultAlert
namespace EndOfServiceAlert{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    EndOfServiceAlert::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace EndOfServiceAlert
namespace InterconnectSmokeAlarm{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    InterconnectSmokeAlarm::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace InterconnectSmokeAlarm
namespace InterconnectCOAlarm{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    InterconnectCOAlarm::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace InterconnectCOAlarm
namespace ContaminationState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ContaminationState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ContaminationState
namespace SmokeSensitivityLevel{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SmokeSensitivityLevel::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace SmokeSensitivityLevel
namespace ExpiryDate{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ExpiryDate::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ExpiryDate

constexpr std::array<DataModel::AttributeEntry, 5> kMandatoryMetadata = {
    ExpressedState::kMetadataEntry,
    BatteryAlert::kMetadataEntry,
    TestInProgress::kMetadataEntry,
    HardwareFaultAlert::kMetadataEntry,
    EndOfServiceAlert::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SelfTestRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SelfTestRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SelfTestRequest

} // namespace Commands
} // namespace SmokeCoAlarm
} // namespace Clusters
} // namespace app
} // namespace chip
