/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/AudioOutput/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace AudioOutput {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace OutputList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OutputList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OutputList
namespace CurrentOutput{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentOutput::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentOutput

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    OutputList::kMetadataEntry,
    CurrentOutput::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SelectOutput {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SelectOutput::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SelectOutput
namespace RenameOutput {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RenameOutput::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace RenameOutput

} // namespace Commands
} // namespace AudioOutput
} // namespace Clusters
} // namespace app
} // namespace chip
