/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Groups/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Groups {

inline constexpr uint32_t kRevision = 4;

namespace Attributes {
namespace NameSupport{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    NameSupport::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace NameSupport

constexpr std::array<DataModel::AttributeEntry, 1> kMandatoryMetadata = {
    NameSupport::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace AddGroup {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AddGroup::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace AddGroup
namespace ViewGroup {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ViewGroup::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace ViewGroup
namespace GetGroupMembership {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GetGroupMembership::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace GetGroupMembership
namespace RemoveGroup {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RemoveGroup::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace RemoveGroup
namespace RemoveAllGroups {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RemoveAllGroups::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace RemoveAllGroups
namespace AddGroupIfIdentifying {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AddGroupIfIdentifying::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace AddGroupIfIdentifying

} // namespace Commands
} // namespace Groups
} // namespace Clusters
} // namespace app
} // namespace chip
