/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/CommodityMetering/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace CommodityMetering {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace MeteredQuantity{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MeteredQuantity::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MeteredQuantity
namespace MeteredQuantityTimestamp{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MeteredQuantityTimestamp::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MeteredQuantityTimestamp
namespace TariffUnit{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TariffUnit::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TariffUnit
namespace MaximumMeteredQuantities{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaximumMeteredQuantities::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaximumMeteredQuantities

constexpr std::array<DataModel::AttributeEntry, 4> kMandatoryMetadata = {
    MeteredQuantity::kMetadataEntry,
    MeteredQuantityTimestamp::kMetadataEntry,
    TariffUnit::kMetadataEntry,
    MaximumMeteredQuantities::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {

} // namespace Commands
} // namespace CommodityMetering
} // namespace Clusters
} // namespace app
} // namespace chip
