/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/WebRTCTransportRequestor/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace WebRTCTransportRequestor {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace CurrentSessions{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentSessions::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kAdminister,
    std::nullopt
);
} // namespace CurrentSessions

constexpr std::array<DataModel::AttributeEntry, 1> kMandatoryMetadata = {
    CurrentSessions::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace Offer {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Offer::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Offer
namespace Answer {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Answer::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Answer
namespace ICECandidates {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ICECandidates::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace ICECandidates
namespace End {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    End::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace End

} // namespace Commands
} // namespace WebRTCTransportRequestor
} // namespace Clusters
} // namespace app
} // namespace chip
