/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <clusters/shared/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace NetworkCommissioning {
namespace Attributes {

// Total number of attributes supported by the cluster, including global attributes
inline constexpr uint32_t kAttributesCount = 16;

namespace MaxNetworks {
inline constexpr AttributeId Id = 0x00000000;
} // namespace MaxNetworks


namespace Networks {
inline constexpr AttributeId Id = 0x00000001;
} // namespace Networks


namespace ScanMaxTimeSeconds {
inline constexpr AttributeId Id = 0x00000002;
} // namespace ScanMaxTimeSeconds


namespace ConnectMaxTimeSeconds {
inline constexpr AttributeId Id = 0x00000003;
} // namespace ConnectMaxTimeSeconds


namespace InterfaceEnabled {
inline constexpr AttributeId Id = 0x00000004;
} // namespace InterfaceEnabled


namespace LastNetworkingStatus {
inline constexpr AttributeId Id = 0x00000005;
} // namespace LastNetworkingStatus


namespace LastNetworkID {
inline constexpr AttributeId Id = 0x00000006;
} // namespace LastNetworkID


namespace LastConnectErrorValue {
inline constexpr AttributeId Id = 0x00000007;
} // namespace LastConnectErrorValue


namespace SupportedWiFiBands {
inline constexpr AttributeId Id = 0x00000008;
} // namespace SupportedWiFiBands


namespace SupportedThreadFeatures {
inline constexpr AttributeId Id = 0x00000009;
} // namespace SupportedThreadFeatures


namespace ThreadVersion {
inline constexpr AttributeId Id = 0x0000000A;
} // namespace ThreadVersion


namespace GeneratedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::GeneratedCommandList::Id;
} // namespace GeneratedCommandList


namespace AcceptedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::AcceptedCommandList::Id;
} // namespace AcceptedCommandList


namespace AttributeList {
inline constexpr AttributeId Id = Globals::Attributes::AttributeList::Id;
} // namespace AttributeList


namespace FeatureMap {
inline constexpr AttributeId Id = Globals::Attributes::FeatureMap::Id;
} // namespace FeatureMap


namespace ClusterRevision {
inline constexpr AttributeId Id = Globals::Attributes::ClusterRevision::Id;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace NetworkCommissioning
} // namespace Clusters
} // namespace app
} // namespace chip
