/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/common/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Pm25ConcentrationMeasurement {
namespace Attributes {
namespace MeasuredValue {
inline constexpr AttributeId Id = 0x0;
} // namespace MeasuredValue

namespace MinMeasuredValue {
inline constexpr AttributeId Id = 0x1;
} // namespace MinMeasuredValue

namespace MaxMeasuredValue {
inline constexpr AttributeId Id = 0x2;
} // namespace MaxMeasuredValue

namespace PeakMeasuredValue {
inline constexpr AttributeId Id = 0x3;
} // namespace PeakMeasuredValue

namespace PeakMeasuredValueWindow {
inline constexpr AttributeId Id = 0x4;
} // namespace PeakMeasuredValueWindow

namespace AverageMeasuredValue {
inline constexpr AttributeId Id = 0x5;
} // namespace AverageMeasuredValue

namespace AverageMeasuredValueWindow {
inline constexpr AttributeId Id = 0x6;
} // namespace AverageMeasuredValueWindow

namespace Uncertainty {
inline constexpr AttributeId Id = 0x7;
} // namespace Uncertainty

namespace MeasurementUnit {
inline constexpr AttributeId Id = 0x8;
} // namespace MeasurementUnit

namespace MeasurementMedium {
inline constexpr AttributeId Id = 0x9;
} // namespace MeasurementMedium

namespace LevelValue {
inline constexpr AttributeId Id = 0xA;
} // namespace LevelValue

namespace GeneratedCommandList {
inline constexpr AttributeId Id = 0xFFF8;
} // namespace GeneratedCommandList

namespace AcceptedCommandList {
inline constexpr AttributeId Id = 0xFFF9;
} // namespace AcceptedCommandList

namespace AttributeList {
inline constexpr AttributeId Id = 0xFFFB;
} // namespace AttributeList

namespace FeatureMap {
inline constexpr AttributeId Id = 0xFFFC;
} // namespace FeatureMap

namespace ClusterRevision {
inline constexpr AttributeId Id = 0xFFFD;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace Pm25ConcentrationMeasurement
} // namespace Clusters
} // namespace app
} // namespace chip
