/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ThreadBorderRouterManagement/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ThreadBorderRouterManagement {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace BorderRouterName{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    BorderRouterName::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace BorderRouterName
namespace BorderAgentID{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    BorderAgentID::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace BorderAgentID
namespace ThreadVersion{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ThreadVersion::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ThreadVersion
namespace InterfaceEnabled{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    InterfaceEnabled::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace InterfaceEnabled
namespace ActiveDatasetTimestamp{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ActiveDatasetTimestamp::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ActiveDatasetTimestamp
namespace PendingDatasetTimestamp{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PendingDatasetTimestamp::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PendingDatasetTimestamp

constexpr std::array<DataModel::AttributeEntry, 6> kMandatoryMetadata = {
    BorderRouterName::kMetadataEntry,
    BorderAgentID::kMetadataEntry,
    ThreadVersion::kMetadataEntry,
    InterfaceEnabled::kMetadataEntry,
    ActiveDatasetTimestamp::kMetadataEntry,
    PendingDatasetTimestamp::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace GetActiveDatasetRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GetActiveDatasetRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace GetActiveDatasetRequest
namespace GetPendingDatasetRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GetPendingDatasetRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace GetPendingDatasetRequest
namespace SetActiveDatasetRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetActiveDatasetRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kManage
);
} // namespace SetActiveDatasetRequest
namespace SetPendingDatasetRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetPendingDatasetRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kManage
);
} // namespace SetPendingDatasetRequest

} // namespace Commands
} // namespace ThreadBorderRouterManagement
} // namespace Clusters
} // namespace app
} // namespace chip
