/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/OccupancySensing/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace OccupancySensing {

inline constexpr uint32_t kRevision = 5;

namespace Attributes {
namespace Occupancy{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Occupancy::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Occupancy
namespace OccupancySensorType{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OccupancySensorType::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OccupancySensorType
namespace OccupancySensorTypeBitmap{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OccupancySensorTypeBitmap::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OccupancySensorTypeBitmap
namespace HoldTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    HoldTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace HoldTime
namespace HoldTimeLimits{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    HoldTimeLimits::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace HoldTimeLimits
namespace PIROccupiedToUnoccupiedDelay{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PIROccupiedToUnoccupiedDelay::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace PIROccupiedToUnoccupiedDelay
namespace PIRUnoccupiedToOccupiedDelay{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PIRUnoccupiedToOccupiedDelay::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace PIRUnoccupiedToOccupiedDelay
namespace PIRUnoccupiedToOccupiedThreshold{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PIRUnoccupiedToOccupiedThreshold::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace PIRUnoccupiedToOccupiedThreshold
namespace UltrasonicOccupiedToUnoccupiedDelay{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UltrasonicOccupiedToUnoccupiedDelay::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace UltrasonicOccupiedToUnoccupiedDelay
namespace UltrasonicUnoccupiedToOccupiedDelay{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UltrasonicUnoccupiedToOccupiedDelay::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace UltrasonicUnoccupiedToOccupiedDelay
namespace UltrasonicUnoccupiedToOccupiedThreshold{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UltrasonicUnoccupiedToOccupiedThreshold::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace UltrasonicUnoccupiedToOccupiedThreshold
namespace PhysicalContactOccupiedToUnoccupiedDelay{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PhysicalContactOccupiedToUnoccupiedDelay::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace PhysicalContactOccupiedToUnoccupiedDelay
namespace PhysicalContactUnoccupiedToOccupiedDelay{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PhysicalContactUnoccupiedToOccupiedDelay::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace PhysicalContactUnoccupiedToOccupiedDelay
namespace PhysicalContactUnoccupiedToOccupiedThreshold{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PhysicalContactUnoccupiedToOccupiedThreshold::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace PhysicalContactUnoccupiedToOccupiedThreshold

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    Occupancy::kMetadataEntry,
    OccupancySensorType::kMetadataEntry,
    OccupancySensorTypeBitmap::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {

} // namespace Commands
} // namespace OccupancySensing
} // namespace Clusters
} // namespace app
} // namespace chip
