/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/OtaSoftwareUpdateRequestor/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace OtaSoftwareUpdateRequestor {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace DefaultOTAProviders{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DefaultOTAProviders::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    Access::Privilege::kAdminister
);
} // namespace DefaultOTAProviders
namespace UpdatePossible{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UpdatePossible::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace UpdatePossible
namespace UpdateState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UpdateState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace UpdateState
namespace UpdateStateProgress{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UpdateStateProgress::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace UpdateStateProgress

constexpr std::array<DataModel::AttributeEntry, 4> kMandatoryMetadata = {
    DefaultOTAProviders::kMetadataEntry,
    UpdatePossible::kMetadataEntry,
    UpdateState::kMetadataEntry,
    UpdateStateProgress::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace AnnounceOTAProvider {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AnnounceOTAProvider::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace AnnounceOTAProvider

} // namespace Commands
} // namespace OtaSoftwareUpdateRequestor
} // namespace Clusters
} // namespace app
} // namespace chip
