/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <clusters/shared/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace JointFabricDatastore {
namespace Attributes {

// Total number of attributes supported by the cluster, including global attributes
inline constexpr uint32_t kAttributesCount = 19;

namespace AnchorRootCA {
inline constexpr AttributeId Id = 0x00000000;
} // namespace AnchorRootCA


namespace AnchorNodeID {
inline constexpr AttributeId Id = 0x00000001;
} // namespace AnchorNodeID


namespace AnchorVendorID {
inline constexpr AttributeId Id = 0x00000002;
} // namespace AnchorVendorID


namespace FriendlyName {
inline constexpr AttributeId Id = 0x00000003;
} // namespace FriendlyName


namespace GroupKeySetList {
inline constexpr AttributeId Id = 0x00000004;
} // namespace GroupKeySetList


namespace GroupList {
inline constexpr AttributeId Id = 0x00000005;
} // namespace GroupList


namespace NodeList {
inline constexpr AttributeId Id = 0x00000006;
} // namespace NodeList


namespace AdminList {
inline constexpr AttributeId Id = 0x00000007;
} // namespace AdminList


namespace Status {
inline constexpr AttributeId Id = 0x00000008;
} // namespace Status


namespace EndpointGroupIDList {
inline constexpr AttributeId Id = 0x00000009;
} // namespace EndpointGroupIDList


namespace EndpointBindingList {
inline constexpr AttributeId Id = 0x0000000A;
} // namespace EndpointBindingList


namespace NodeKeySetList {
inline constexpr AttributeId Id = 0x0000000B;
} // namespace NodeKeySetList


namespace NodeACLList {
inline constexpr AttributeId Id = 0x0000000C;
} // namespace NodeACLList


namespace NodeEndpointList {
inline constexpr AttributeId Id = 0x0000000D;
} // namespace NodeEndpointList


namespace GeneratedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::GeneratedCommandList::Id;
} // namespace GeneratedCommandList


namespace AcceptedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::AcceptedCommandList::Id;
} // namespace AcceptedCommandList


namespace AttributeList {
inline constexpr AttributeId Id = Globals::Attributes::AttributeList::Id;
} // namespace AttributeList


namespace FeatureMap {
inline constexpr AttributeId Id = Globals::Attributes::FeatureMap::Id;
} // namespace FeatureMap


namespace ClusterRevision {
inline constexpr AttributeId Id = Globals::Attributes::ClusterRevision::Id;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace JointFabricDatastore
} // namespace Clusters
} // namespace app
} // namespace chip
