/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace JointFabricDatastore {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 20;


namespace AddKeySet {
inline constexpr CommandId Id = 0x00000000;
} // namespace AddKeySet

namespace UpdateKeySet {
inline constexpr CommandId Id = 0x00000001;
} // namespace UpdateKeySet

namespace RemoveKeySet {
inline constexpr CommandId Id = 0x00000002;
} // namespace RemoveKeySet

namespace AddGroup {
inline constexpr CommandId Id = 0x00000003;
} // namespace AddGroup

namespace UpdateGroup {
inline constexpr CommandId Id = 0x00000004;
} // namespace UpdateGroup

namespace RemoveGroup {
inline constexpr CommandId Id = 0x00000005;
} // namespace RemoveGroup

namespace AddAdmin {
inline constexpr CommandId Id = 0x00000006;
} // namespace AddAdmin

namespace UpdateAdmin {
inline constexpr CommandId Id = 0x00000007;
} // namespace UpdateAdmin

namespace RemoveAdmin {
inline constexpr CommandId Id = 0x00000008;
} // namespace RemoveAdmin

namespace AddPendingNode {
inline constexpr CommandId Id = 0x00000009;
} // namespace AddPendingNode

namespace RefreshNode {
inline constexpr CommandId Id = 0x0000000A;
} // namespace RefreshNode

namespace UpdateNode {
inline constexpr CommandId Id = 0x0000000B;
} // namespace UpdateNode

namespace RemoveNode {
inline constexpr CommandId Id = 0x0000000C;
} // namespace RemoveNode

namespace UpdateEndpointForNode {
inline constexpr CommandId Id = 0x0000000D;
} // namespace UpdateEndpointForNode

namespace AddGroupIDToEndpointForNode {
inline constexpr CommandId Id = 0x0000000E;
} // namespace AddGroupIDToEndpointForNode

namespace RemoveGroupIDFromEndpointForNode {
inline constexpr CommandId Id = 0x0000000F;
} // namespace RemoveGroupIDFromEndpointForNode

namespace AddBindingToEndpointForNode {
inline constexpr CommandId Id = 0x00000010;
} // namespace AddBindingToEndpointForNode

namespace RemoveBindingFromEndpointForNode {
inline constexpr CommandId Id = 0x00000011;
} // namespace RemoveBindingFromEndpointForNode

namespace AddACLToNode {
inline constexpr CommandId Id = 0x00000012;
} // namespace AddACLToNode

namespace RemoveACLFromNode {
inline constexpr CommandId Id = 0x00000013;
} // namespace RemoveACLFromNode

} // Commands
} // JointFabricDatastore
} // Clusters
} // app
} // chip
