/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/WakeOnLan/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace WakeOnLan {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace MACAddress{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MACAddress::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MACAddress
namespace LinkLocalAddress{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    LinkLocalAddress::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace LinkLocalAddress

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {

} // namespace Commands
} // namespace WakeOnLan
} // namespace Clusters
} // namespace app
} // namespace chip
