/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/TargetNavigator/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace TargetNavigator {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace TargetList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TargetList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TargetList
namespace CurrentTarget{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentTarget::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentTarget

constexpr std::array<DataModel::AttributeEntry, 1> kMandatoryMetadata = {
    TargetList::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace NavigateTarget {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    NavigateTarget::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace NavigateTarget

} // namespace Commands
} // namespace TargetNavigator
} // namespace Clusters
} // namespace app
} // namespace chip
