/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/AdministratorCommissioning/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace AdministratorCommissioning {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace WindowStatus{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    WindowStatus::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace WindowStatus
namespace AdminFabricIndex{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AdminFabricIndex::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AdminFabricIndex
namespace AdminVendorId{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AdminVendorId::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AdminVendorId

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    WindowStatus::kMetadataEntry,
    AdminFabricIndex::kMetadataEntry,
    AdminVendorId::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace OpenCommissioningWindow {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    OpenCommissioningWindow::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kAdminister
);
} // namespace OpenCommissioningWindow
namespace OpenBasicCommissioningWindow {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    OpenBasicCommissioningWindow::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kAdminister
);
} // namespace OpenBasicCommissioningWindow
namespace RevokeCommissioning {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RevokeCommissioning::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kAdminister
);
} // namespace RevokeCommissioning

} // namespace Commands
} // namespace AdministratorCommissioning
} // namespace Clusters
} // namespace app
} // namespace chip
