/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Switch/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Switch {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace NumberOfPositions{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    NumberOfPositions::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace NumberOfPositions
namespace CurrentPosition{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentPosition::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentPosition
namespace MultiPressMax{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MultiPressMax::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MultiPressMax

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    NumberOfPositions::kMetadataEntry,
    CurrentPosition::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {

} // namespace Commands
} // namespace Switch
} // namespace Clusters
} // namespace app
} // namespace chip
