/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace GeneralDiagnostics {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 3;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 2;

namespace TestEventTrigger {
inline constexpr CommandId Id = 0x00000000;
} // namespace TestEventTrigger

namespace TimeSnapshot {
inline constexpr CommandId Id = 0x00000001;
} // namespace TimeSnapshot

namespace TimeSnapshotResponse {
inline constexpr CommandId Id = 0x00000002;
} // namespace TimeSnapshotResponse

namespace PayloadTestRequest {
inline constexpr CommandId Id = 0x00000003;
} // namespace PayloadTestRequest

namespace PayloadTestResponse {
inline constexpr CommandId Id = 0x00000004;
} // namespace PayloadTestResponse

} // Commands
} // GeneralDiagnostics
} // Clusters
} // app
} // chip
