/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/WaterHeaterManagement/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace WaterHeaterManagement {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace HeaterTypes{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    HeaterTypes::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace HeaterTypes
namespace HeatDemand{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    HeatDemand::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace HeatDemand
namespace TankVolume{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TankVolume::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TankVolume
namespace EstimatedHeatRequired{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    EstimatedHeatRequired::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace EstimatedHeatRequired
namespace TankPercentage{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TankPercentage::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TankPercentage
namespace BoostState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    BoostState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace BoostState

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    HeaterTypes::kMetadataEntry,
    HeatDemand::kMetadataEntry,
    BoostState::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace Boost {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Boost::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace Boost
namespace CancelBoost {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    CancelBoost::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace CancelBoost

} // namespace Commands
} // namespace WaterHeaterManagement
} // namespace Clusters
} // namespace app
} // namespace chip
