/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/FanControl/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FanControl {

inline constexpr uint32_t kRevision = 5;

namespace Attributes {
namespace FanMode{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    FanMode::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace FanMode
namespace FanModeSequence{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    FanModeSequence::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace FanModeSequence
namespace PercentSetting{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PercentSetting::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace PercentSetting
namespace PercentCurrent{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PercentCurrent::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PercentCurrent
namespace SpeedMax{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SpeedMax::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SpeedMax
namespace SpeedSetting{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SpeedSetting::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace SpeedSetting
namespace SpeedCurrent{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SpeedCurrent::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SpeedCurrent
namespace RockSupport{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    RockSupport::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace RockSupport
namespace RockSetting{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    RockSetting::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace RockSetting
namespace WindSupport{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    WindSupport::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace WindSupport
namespace WindSetting{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    WindSetting::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace WindSetting
namespace AirflowDirection{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AirflowDirection::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace AirflowDirection

constexpr std::array<DataModel::AttributeEntry, 4> kMandatoryMetadata = {
    FanMode::kMetadataEntry,
    FanModeSequence::kMetadataEntry,
    PercentSetting::kMetadataEntry,
    PercentCurrent::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace Step {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Step::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Step

} // namespace Commands
} // namespace FanControl
} // namespace Clusters
} // namespace app
} // namespace chip
