/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ZoneManagement {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 5;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 1;

namespace CreateTwoDCartesianZone {
inline constexpr CommandId Id = 0x00000000;
} // namespace CreateTwoDCartesianZone

namespace CreateTwoDCartesianZoneResponse {
inline constexpr CommandId Id = 0x00000001;
} // namespace CreateTwoDCartesianZoneResponse

namespace UpdateTwoDCartesianZone {
inline constexpr CommandId Id = 0x00000002;
} // namespace UpdateTwoDCartesianZone

namespace RemoveZone {
inline constexpr CommandId Id = 0x00000003;
} // namespace RemoveZone

namespace CreateOrUpdateTrigger {
inline constexpr CommandId Id = 0x00000004;
} // namespace CreateOrUpdateTrigger

namespace RemoveTrigger {
inline constexpr CommandId Id = 0x00000005;
} // namespace RemoveTrigger

} // Commands
} // ZoneManagement
} // Clusters
} // app
} // chip
