/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ZoneManagement/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ZoneManagement {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace MaxUserDefinedZones{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxUserDefinedZones::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxUserDefinedZones
namespace MaxZones{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxZones::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxZones
namespace Zones{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Zones::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Zones
namespace Triggers{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Triggers::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Triggers
namespace SensitivityMax{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SensitivityMax::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SensitivityMax
namespace Sensitivity{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Sensitivity::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace Sensitivity
namespace TwoDCartesianMax{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TwoDCartesianMax::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TwoDCartesianMax

constexpr std::array<DataModel::AttributeEntry, 4> kMandatoryMetadata = {
    MaxZones::kMetadataEntry,
    Zones::kMetadataEntry,
    Triggers::kMetadataEntry,
    SensitivityMax::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace CreateTwoDCartesianZone {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    CreateTwoDCartesianZone::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace CreateTwoDCartesianZone
namespace UpdateTwoDCartesianZone {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    UpdateTwoDCartesianZone::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace UpdateTwoDCartesianZone
namespace RemoveZone {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RemoveZone::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace RemoveZone
namespace CreateOrUpdateTrigger {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    CreateOrUpdateTrigger::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace CreateOrUpdateTrigger
namespace RemoveTrigger {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RemoveTrigger::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace RemoveTrigger

} // namespace Commands
} // namespace ZoneManagement
} // namespace Clusters
} // namespace app
} // namespace chip
