/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ThreadNetworkDirectory/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ThreadNetworkDirectory {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace PreferredExtendedPanID{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PreferredExtendedPanID::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace PreferredExtendedPanID
namespace ThreadNetworks{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ThreadNetworks::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ThreadNetworks
namespace ThreadNetworkTableSize{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ThreadNetworkTableSize::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ThreadNetworkTableSize

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    PreferredExtendedPanID::kMetadataEntry,
    ThreadNetworks::kMetadataEntry,
    ThreadNetworkTableSize::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace AddNetwork {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AddNetwork::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kManage
);
} // namespace AddNetwork
namespace RemoveNetwork {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RemoveNetwork::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kTimed),
    Access::Privilege::kManage
);
} // namespace RemoveNetwork
namespace GetOperationalDataset {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GetOperationalDataset::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace GetOperationalDataset

} // namespace Commands
} // namespace ThreadNetworkDirectory
} // namespace Clusters
} // namespace app
} // namespace chip
