/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <clusters/shared/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace IcdManagement {
namespace Attributes {

// Total number of attributes supported by the cluster, including global attributes
inline constexpr uint32_t kAttributesCount = 15;

namespace IdleModeDuration {
inline constexpr AttributeId Id = 0x00000000;
} // namespace IdleModeDuration


namespace ActiveModeDuration {
inline constexpr AttributeId Id = 0x00000001;
} // namespace ActiveModeDuration


namespace ActiveModeThreshold {
inline constexpr AttributeId Id = 0x00000002;
} // namespace ActiveModeThreshold


namespace RegisteredClients {
inline constexpr AttributeId Id = 0x00000003;
} // namespace RegisteredClients


namespace ICDCounter {
inline constexpr AttributeId Id = 0x00000004;
} // namespace ICDCounter


namespace ClientsSupportedPerFabric {
inline constexpr AttributeId Id = 0x00000005;
} // namespace ClientsSupportedPerFabric


namespace UserActiveModeTriggerHint {
inline constexpr AttributeId Id = 0x00000006;
} // namespace UserActiveModeTriggerHint


namespace UserActiveModeTriggerInstruction {
inline constexpr AttributeId Id = 0x00000007;
} // namespace UserActiveModeTriggerInstruction


namespace OperatingMode {
inline constexpr AttributeId Id = 0x00000008;
} // namespace OperatingMode


namespace MaximumCheckInBackOff {
inline constexpr AttributeId Id = 0x00000009;
} // namespace MaximumCheckInBackOff


namespace GeneratedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::GeneratedCommandList::Id;
} // namespace GeneratedCommandList


namespace AcceptedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::AcceptedCommandList::Id;
} // namespace AcceptedCommandList


namespace AttributeList {
inline constexpr AttributeId Id = Globals::Attributes::AttributeList::Id;
} // namespace AttributeList


namespace FeatureMap {
inline constexpr AttributeId Id = Globals::Attributes::FeatureMap::Id;
} // namespace FeatureMap


namespace ClusterRevision {
inline constexpr AttributeId Id = Globals::Attributes::ClusterRevision::Id;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace IcdManagement
} // namespace Clusters
} // namespace app
} // namespace chip
