/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/IcdManagement/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace IcdManagement {

inline constexpr uint32_t kRevision = 3;

namespace Attributes {
namespace IdleModeDuration{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    IdleModeDuration::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace IdleModeDuration
namespace ActiveModeDuration{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ActiveModeDuration::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ActiveModeDuration
namespace ActiveModeThreshold{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ActiveModeThreshold::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ActiveModeThreshold
namespace RegisteredClients{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    RegisteredClients::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kAdminister,
    std::nullopt
);
} // namespace RegisteredClients
namespace ICDCounter{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ICDCounter::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kAdminister,
    std::nullopt
);
} // namespace ICDCounter
namespace ClientsSupportedPerFabric{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ClientsSupportedPerFabric::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ClientsSupportedPerFabric
namespace UserActiveModeTriggerHint{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UserActiveModeTriggerHint::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace UserActiveModeTriggerHint
namespace UserActiveModeTriggerInstruction{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UserActiveModeTriggerInstruction::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace UserActiveModeTriggerInstruction
namespace OperatingMode{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OperatingMode::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OperatingMode
namespace MaximumCheckInBackOff{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaximumCheckInBackOff::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaximumCheckInBackOff

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    IdleModeDuration::kMetadataEntry,
    ActiveModeDuration::kMetadataEntry,
    ActiveModeThreshold::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace RegisterClient {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RegisterClient::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace RegisterClient
namespace UnregisterClient {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    UnregisterClient::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace UnregisterClient
namespace StayActiveRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    StayActiveRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace StayActiveRequest

} // namespace Commands
} // namespace IcdManagement
} // namespace Clusters
} // namespace app
} // namespace chip
