set(SDK_PATH "/Volumes/Resources/git/matter/stash/third_party/silabs/gecko_sdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.3")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/common/src/sl_utility.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/rsi_debug.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/sl_si91x_stack_object_declare.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/src/sl_si91x_button.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/led/src/sl_si91x_led.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_sysrtc.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/src/sl_sleeptimer_hal_si91x_sysrtc.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_driver_gpio.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/syscalls_stubs.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/BytesToHex.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/../../mbedtls/repo/library/aes.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1parse.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1write.c"
    "${SDK_PATH}/../../mbedtls/repo/library/base64.c"
    "${SDK_PATH}/../../mbedtls/repo/library/bignum.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ccm.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher_wrap.c"
    "${SDK_PATH}/../../mbedtls/repo/library/constant_time.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ctr_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdh.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdsa.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp_curves.c"
    "${SDK_PATH}/../../mbedtls/repo/library/entropy.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hkdf.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hmac_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/md.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pem.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pkcs5.c"
    "${SDK_PATH}/../../mbedtls/repo/library/platform.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha256.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha512.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509_create.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/src/startup_common_RS1xxxx.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/si917.cpp"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
    "../autogen/sl_si91x_button_instances.c"
    "../autogen/sl_si91x_led_instances.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/inc"
    "${SDK_PATH}/../../mbedtls/repo/library"
    "${SDK_PATH}/../../mbedtls/repo/include"
    "${SDK_PATH}/../../../src/lib/support"
    "${SDK_PATH}/../../../src/platform/silabs"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/service/bsd_socket/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/config"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/service/network_manager/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/board/silabs/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_api/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/led/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/protocol/wifi/inc"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/resources/certificates"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/resources/html"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/resources/other"
    "${SDK_PATH}/../../../../../stash/wifi_sdk/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    DEBUG_EFM=1
    MBEDTLS_CONFIG_FILE="siwx917-chip-tinycrypt-config.h"
    NVM3_LOCK_OVERRIDE=1
    OPTIMIZE_TINYCRYPT_ASM=1
    SILABS_PROVISION_PROTOCOL_V1=0
    SL_MBEDTLS_USE_TINYCRYPT=1
    SL_PROVISION_CHANNEL_ENABLED=1
    SL_PROVISION_GENERATOR=1
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4002A"
    SL_BOARD_REV="A06"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    SL_SI91X_BOARD_INIT=1
    SRAM_BASE=0x0cUL
    SRAM_SIZE=0x2fc00UL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    DEBUG_ENABLE=1
    DEBUG_UART=1
    ENABLE_DEBUG_MODULE=1
    FLASH_PAGE_SIZE=1
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    SI91X_PLATFORM=1
    SI91X_SYSRTC_PRESENT=1
    SL_SLEEP_TIMER=1
    __WEAK=__attribute__((weak))
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQtz5LaV7l+ZUm3dSnZbzZFmbI/n2klpWj1jbaSRSt1jxzdKsdgkupsRX+ZDLTmV/37x4JsgCZAA2JNd78ZWk8T5vnPwBg4O/nlyd3/738vFWr+/vV2fvD/558PJ/fL6Yn3181Ivv3o4ef9wMp8/nPzrZJanWd1+uV8sVzDZD39+dp1XTyCMbN/78eHkbP764eQV8Ezfsr0dfPBl/fH03cPJn//04P0QhP4/gBm/gkm86L3rW8CBX+zjOHivaYfDYR7ZjrGJ5qbvalGkreLEsv05MP0QQKEwdQDC+GVlwv/CdKm0hxMo+tWrH7a+Y4HwlWe46KXpe1t7l75Db20HZO9Wy0+flvf6/XqtL+Bn8z0UnoQ2fIO+eq/97DuJCyLtHkR+Eprwr50da64RxyDUotiI9hrEfrKRylqUBIEfxlpkf3/2nUZgNQqCRmMSOboHYt0CWyNxYv3JcBIQSeDTikNl9TEE4H59u1rgxBLoNAHarIOSPesOsHRTFpkWFCqj+/VSvwRPtgl0KEECmSZAm2U2vhFmfJPQiKFIOcZpAerlFYe+I5lRBkHlEtievEJTFd5dejdJHPueLpVPNxgTv03svVZHsIbGyvBMKcMzFoYOAEFsuyCUS40G0201KNp8hH//DhQYjQpG5Qdcx97oqE+H/dEm2ckj14FEmP2gkUEDbQBhJLG/Ax59BFEvK7YHCXmQ49wUp0XKoFEwK2BMFadIIdDI/fSY+nU1pmsg8RCTabQGEpWYY3uPIERP9JW/mDuWeEYUiNYh0MJ3A98DXizFNk2Etswys69004gNxxfaiJSyiorTRgo8oQ/3hmc5IJREqIHBRkZODWtgtJGx/SgOgeGm38qqWDQYZkpyTESD6aVke3YsvRXqQKMSnJuhmfWj8E/xnBoA/V31wY4ATOEBM36jR9aj/mb+Bi1D5PxrKwNZ05J/0fjGwlOw0vvGF2SlovIF5RvYwtc+aXzkmknjEwrnEFC+an63twPqd01uyLTUDxuf2nc3X3SYbbvWBPQklh+3Y5BEpYIVRrYevUQxcNPcxxNgtgJGStbB3too+7UihzWSkRrJLVzSnjVocQ0ZVEPW0qAhtFxDLSeutfLRWDWyAzfRjcBmbVRkaFHh0M68Urv4X1daMGIzTFKR4nXINj2rPGMjjJNALdE6JhNTVBKDSA9hI71NPFMRVwoqM1sLzlXxhFWPfJV8G7h0xp3Fud6SeV3tZE1vEIY+65BvjL6QlFbBY8qZjREBPX4JmMcSYylWAZk4WnB8rZRjFZCJ4/3q7Bn+o4hgCY25/plmgOYsLvOSsIjCWAVl5wplqGSZwg1qedXRrKEys62MWBTybeAyMYYpCIQiphU8VoZKK1IFj5WhEUUgjNUxLPB4apHyMlnBZBsTlgeSaojWIdl44qVDpVWnDsnB031S1cBX8LjHfl2vOp0LOr/tnmjXqokHtYRTONsP7dgGefmVO4JOd3LSMXQ7hUGDacrIJIl498rGadaC26IOY5aoIt4OT+PPU4RRLyOhCOOdNtklFnEvzfpSRLY2qbpj6W+QDxGUYTpGCJTx7mWheOZKbCi5UGPts945RxTXTre/qK3uhjZyWGNaUHUjO9JJArbKsrhZXa1Yl1YvuwRTvr/yTCex6EvBRZJS3hIAtJ0mcwybGlQrW0vDhtAIAS0lrjX4MK+mZikvPh+RGoQMrw7L9U/Ho0NKZoAO+s3F4qj0yAgN0eXup1+PS5eUEK8uHx3I7ng0yenw6nF1fkRlKyXDq8PN4up4dEjJ8Orw+eLz5fEokbHh1WJ1cUQ5kZLh1uHumHS4G6TDl9XF/fp4tMjp8Ovx4Zi0+DBQhyOq2RmbAVoc0WAqYyNnp51n9te5RCXiVIMga/aee+AywXHMfBgnORW6S+WD6WXnaLlC7pPyvudTZwdTIad8pNg5GqxQUz4A7BzkVajB6YV+ffH53Xdvzy/UcqwjM5BVPnzrHKJVqamuGewV48vljeKszRBZyKkfCfaM9mr0FA/wOgdxzWyVtU7dnq3ta9LNbFXLLoMctyES+i7XOi/X8joSbjqP8pyaMssUWuQL7WVs5v16lAjsAtufinEOzu5iYJiPtidvE6ODcAmay8JmKM+nqK9EhHyORTiNPB+TPrZ83ia4AG2TSJ5zRF/pzcC5KG9tdyrCKTQX3V1gucZUhHNwLsqBf4ATs8h4mqxkVBnwkT9MVjxSaC66v0WBPRXfDJuLcDhN51GC5qIbGxsH6LKdkXuIN0gMUEGuux2TAnzud3ladBx/MuIZOBflZMImOxnSYqNE+iE0gmA6U9c58CngBFGEBuCTsS8TkOgUCY1jB3sQGk7Kgu5gM9y7zHR881FPAsuI5TlqZcZsaoP9tuoc2I85hPIOQvVwLsEz0yXTrwkJ5wR4jj6E8aRGLhgwk8atuLwDogykCwbMpHFDPiHlDJ+LcN6AT0y8zINdgcgI40mZZwQU+qVW2lrZnSdFd9SJ1jlwtfcTcS7Bc7b3ExLmW+8zkmc9BFsQAs8E+pPvxLL98ntU6CTEnAuGNWmhSeE5jpnKn+B3lXGTb46PUI3QiCUe0WZhXWHBTl7+2msXab71V5M5MJQktnybHZYxabVL4dnbaiUr211tNffqNvD2KKyQpWSJu4t5jQezAhPz5qWrZmm+gzD/8vxOxXJxF2PeJWP7fNJWI4XnoDtpm5zCs9OdtJO2+TpnPzBceWecGfjmBNh3yxVsJnUQ5t1Q+g1M2jik8Ox0J27MuPe/UAIUOyyedBJYZcG+zK5g466DNffm3dSdc8jdOUeW7cs/VdZBOSfAQdkFkzZxOQF2ytMuwUScDleRa09bJlJ8dsLTNsq8bXI0NV9uwmT/Y0rKOQNO0voeGBbaB5mcfJkJ7zbShOQLBnzbSBNS5vZHUOqL0EN8kD8C2cWZknlGgJnyk2FNSTiFZ6Z7SEL5rkwdfDN8vlA47ls9mKz1aLKQ6KSSeJA4sFBIZMHeKbkaRDddiQNFSZ1qWKEaCYW7tlQKsotW2Q6VMlUjwVotJubOxFpofZDuvJXnSAlJaRVpcW7o4jVFranTUFX6+hpnCi++PuaotBmuguxwsEM06Q0ZK6Sp2BuhdTDQXVo8DQS5FIo1HlpXc9KWKwRBejtSV18juNVGpODSWrL6rlJgbj967CG7gLbZo1I6Cy6D7MHT1DrAklnKoHj1RQyCVstXymK6woUIKC9ZyAyVYpWyEF2m2NvCCIRIB7Ym0Hty38gsmqT117co1Jpue/FWekFN1deQZtUCSuXSEQ2HqhASq+9hj4fFTKhNk4jymocpZPc2K/JxrBgEVbwWErz52iwcyjXp5iK9kypucZXUIBS3xKJiS1RVdDAis3XBIa9M3awm6M3sGidlBbFkHFIcaUwm7NfwbQQOeAKOhCgYG1/+4KGkQb4omuKy+4NGio520siWwdm9pQI3mYRtBszud+QoqGwUoikuO8+JDMptT3URDah0h4UzCEIf8ol8mBR4kQKHfCp3Cgl2Jx6wU+JPQCNewubgG0M8W8HCAJ1xCZ2dswJnAipbThcCKCCYsiDX8Lm8BvAC40T9cg2ffRtb2ZF6GmuG8/S0jeGDJX/nnUY3Ax6/mcF1DQweGEifcpT0zU6qZsBcI5IpiKa4Q3r6SehW4Lna8Cnoch/EL7WhU/Ct4Q9qwyfhXcUf0IZPwbqCzteGT0E3Axa3u9fyou1xtSM42CFw4Mi5/956F7h++NJy0VLJuq7hOL6pb5LtFkgKh5GR1ggnrQnZtC7rhVIgDD2f5Tqp9i6UvmKKBcs1B4aoLnvnqOMiqravDVWUJWgyhkY1HfHtpRkYl2qs5QBa0AOxjIIAxaJVahB6aAEV3Rknt1QQTWq7IVQODEGBiTAdN7yx7djxi0ryFGh2zkRzpPUuNNAEVt8bnuVICiPToUEnETZ9ilw0Q2Ch+bjhSG5r24pRjYCSdoZSFKQ2Oqnu6a4TBVpEKVSsQScRTn0m4S6t6bdNN+gf56RUAhQsWmrFQ3S0GhpV7zZ2UjOnwY6aK6ym39qhi/1FkgCWypbbMSuK1lLgkiw3P+oc6w9yCr2ZRE0oNbfYuI/KwrbhUJdnueSeq+lNz1qH1I1zCEeGwU2LPwacAm3Q9cPbEL45+KHsQWXFU4gKPrwIxfsQGBZsTFgKkp0dOUmc2CYpJfn35crn/LQO+OHq7/0o1l0zYZp8IHCmIZN9eP7+7Ds9ghNlzwx0BCLXSpka6fM2AlK6cGO/IfObrdHi2jdsEofqJ/J7gWqhM06wuMu1YUWPfA2pyYBtvBY4Rrz1Q+Wca9B8ZPVM8ISsKxx4ZmibZAraFWwmuqgVy6unesYNeAbS9YrgT14VfY7STbKIeAdNVUBydCVz9jRgoqwDNy0Kl0I1sl/gSCL5xYYevwRAzmHaHrpVdFbKZGg7Bd0cmZGq+3YKmgSVkaI/Scb7PBkePMIB1s6V44zQQ7SMzUg3iaYpnRkuI82DHQHUpOdnVyIQJ3JCwvUQb2fCqopjeJl7vMQDB31qUFnwqGCBre1N0xLX8QcMpxSzpsBzkpbnMc1Iu8drunHEHyOpJ1wClrMQ3TKy6lqlkrvY6zVWqdp0p69S+R5E9iSFlK7TpGDyUEWLolhJW3bLU+NbB2YnrWIESInJwUcSrwvlVUkh2SYwO2nbj1Fj+ggkD7YqhKug7GRx2E3Td1TMX6qRJRrA7KRRvNAp2ocGLgfl2IgTpVxzQHaSqssAV9ZjKBXdd0qxhse8Rk99THnYeNR80H/6vH7mHMRoS0V3Dc/YNU6bMqxj0zaGN0Zkm0KdR/LzuVW6ZccXKmg9D9rZwtYFvVNItYzIztMEYQxRTSOGM7YYducKbUuDZmCugGGTCb1SsexvtTuiSNOD7GHVoPj1oQ3padqI6wnbNCq503R2fzR2lqeEVwrDwsgOBHV0DLTKWCzclBHjYoUxlFGrorG0SPJJNZmw9OiNKr2JrHSU3t0191Z9SMnaCNO7oEXifmTCO20Pv7KJb7BEHiUEFjLfwm+/lUwnx+gumXAsKeDyrhYqhfRuEmJmoW0kWqebVRIv4lqNOoOX/iYiERB/sAU+oUUTFDHS3/hGaHWN88nEZeTwnsTIgEijR0JYSj6bCrPwG6loCSOfQv7YrK1QLyKHpKI7S1b+ZbpTkYRivDLbKTWB+npHHCdSkqUa4vvI2OemRC4V6X1UgoMrkUpFeh+VSGoORTwZlF5FIJFNDUB805ktK3a1nojt+KURrLMEX9pMA/wymxR3gMmaKCNI0cpkM+NMtpxJcZuxxpboqjLlZUI6WF91I0mFzd476PFM2nEKwRsv7dT6N1qo/MRMRttpMU8/cUmWxkNOG0n8KzrHl432r663qJMOhEvWzLWcZ+ifWDebhTphw7JsNGoih1hF7MWk1NPsosrXOimZbmRHwnbjq3QasnuoCGuFajTaW57G6BAA8O71uaCqXaXRkN1DRdQKYY1F62JgW+0Si99SGvraj/rPas0LMyql+ldvb4qdhqjW6pTUNg4oNIcNeZe3JuYBcOfm0OuLcnJamYPWD6UxsAxC+wltnjyCF5wU/VcSyxaoTpYQJNzawIGzRgMnEs2NBtDO6PckBPrGcGLbRV4rMji1QrSyMg0kQTiTqth2dJy5chg0RPewyEqWeBIlya0c0AIbCKVYoim6h4UMSzQkt3JAkrATsmgKdcHtVsAz9nL7KN4crRCMrKTkURtCKyf3xQJPj3Zc70NEsurA6OUlw0oU2X15Zu2QBBktfhtAKyNgBMJJlGRqbUOoxpBoH7v1JaoSTcffDd1VK0giCC2X1GqSPXAc/+CHzsAVvxpgVVwrKpzxPtkRnC4NDjpRw60LZM8KP97XPKUqTG3PAs9zhDGWJwbSqvJaaVZ+Vn9U6e+A+egjJP3t/O28uHGkvi6aHk/tGKX3rgowTLJj37VZTzG4Rhwjdxlsr3hvh5YeGGH8kq0Z55ppGfn6lDtH655NbWzW6cNoSikUy7zfj875DjmOJkfD7WRql5KA51iHyI8oDLUdxcyu42NZ93LotjXwEtbmfrR9M6xuRkYUAeb57Pg6kqP1LQApLYls5Q9OMUP2DmI0qwKth5UDC58yUhlYn6U41jQFWIq2wtm/TNu7rtxd29kWm4drl0UY6OHAVL/VcC2hMdUkRawKNJaapIpUBsaz+Nkowoub1dWqa5S08MN6GJnaF1ee6SSUgGXVZRlcBtFars0e8W+AjbA+GiKtpby0JnTnLhj5HEUxZvd+EUm0hNzJM/4dbUfEsEorJVmFZbDkzpQ4gm61YorazQ8vqzIHZBBErwTayc4NEt0I3afvlNKroApwEb5f367OhbUfsA+TbQ1MuFaYUtjO7PLRjVcmq1eGIHolUH7fkxXm0212CIBCudvMkZpHKkY4aVVY8S4DDGfPyFE53fbsHud2FueqkjDdg3/KM2bm21tCzAYMNBJyPJYaSNIqBU3dSoSCKgkBDZrtw9EgMNzxhSKTJL8wZEhZSSgj93q5pt/qYSxxaNvHNEOXU15ze0gvp7l+mQ9FCZkrJyZjmqELqErkkpDxFYnIwTVdfgklYPkkrArN4JGMPn8EoQdY72sSzbUAl1OZyiaRXkpTDQt/7DI0X25Mw7UAF1Gh2i5mHlKpclkKymnHZcsM1coedg+ySMI0CpKqV2EZlWrmy7dldI58mYBsHV78NAK4VvjUNYmgbELyZzowfYvVZ32A/bAS5QXxHE9Ai4SurB97NhiKQGHojMSR2KEQKyAscji2Btp9Whd+rJQZEyN9BzwQypx80WxWAu1nKLWtprFruZqeykzfOhBMOb8Ctp+l48tccKIRzBAHnNLqG3OUq1wWM9OxvUeZA5CSiqgf76bAmB9KyWaI/Pnh2Jvu/IAfYIjFzVu8mm4o0AtiahRcGT13XX++rV04cjfZwxsNMgqyBcrnEpTQQ0SZXIntB1IBjygKqI4N1PQrFf1WjVhbrzXuKAk6n9Lun1ai2lUOtyEAYez3BEfA2xSU6syy3t+60SK6bCN7VL7IdCO7LNnaf4VAo81lutq1bUeppmqGL2VbqU/bbAunToISmI/K2Q18X/zoiZt1ToMpp1g6JrIi0leYAz+MjY1Dz+PKl58WC5ZrcC7ub1CX85HlQgcErrB6EItomcoa1EjL6GoZF4Z40ehT1zBD1ggySrjnhKTEkb4B7o3BcpvWHhiB/nbCTE2ZagWRcSE6acMBlkZRks9zryFSelqbF3SDKCw2CYpgNR3VMoMeshYIQoAOWFgkoj4+Wy3ev5GZejufHkXAEzpOtIOaBxPSr7PoIf0RikH+BdMRLjPoISvFG5eZKN09t0EScomMHUgvnp+ObpNHH/EgIbG6eU7EyyDe4MFA/BAaQQDCiWmXWfSQznq36QiXGfSRDf1/wMZwQuuWGfSQ/S0ByYRmzeF7aEbADfYTtg8Ffh/RGMU7woPRCQtAnUUP6RX6/GZizjUSvXbGTiRT9xsNGj200aGJ6dhm6H0k0U7nhCWhwGdetqGN55XPwcrInYv8lWGncpp19E6qUk6i9FKkHUlp6bqUc8thu70WKg2DcpIN+O4jILBdmKAg5rDd5EhroJ5djivCowrs+i8ewZ5cTzY49K7ALz99Wt73rcCQr/T79Vq+8Yh+WqGCRtC1Kom+cQj+WH7H08OWZcRUqDU124zE0IVzrs2pWsiF8npfEMzNIOA3Rh6iQsO7Z0bsh1ouTGsCuYbtiUMqpFGgUGDW78RhlcRRwC5ganSAGKb5C3PItAomeDbcwIFvCp82UrgKMk2QXiY3G2ANswE3nwKKwuouS7TYG95AR1sGRjQYBja4gZNkpFasLl5LD7nfDZoa8VAqwbCwkW6iClAXoxtymYls+5RgWNhIt08FqIvRXRp8V7aByjgsfH4+k2+kOhYTr3OFvM77ea1gjwNzWnb2lWAY2Hwa7pIzgNSnujdOt6WkZ18FiIHRIoli31XGqwzHwO4y9WpWRa+CR+H3wYjAt4PO4CPvOOwllwRomV8rJLXDDNK6BahVoxc4OFr7P6HAaALAKtK64cRoV5NHgVz8dHV37e92A6MZ1REdIkqriaUAr8FzfOs5L9lXQhTO4KnCKSRWuMgv8OU1Q9Wv15+6zD7YwYp3ArdpPNrcddQ+E6Ma9uYdGRQONXEE4iSAc/EXxzcsrS6xD3Swqh2wXdXpLrXQDXD9cNA0sl6s6VJp0+WXCN34gUJgJ5tIcMdAE07hYDBfbtu6IuPCWWjsRFoIAh8ZIjTCF80oX2FbRYy8M5gwGr0UTcctS29BP4R2LA89l05B36QdmAToQjQN196hoIJScHPRFFzTlAOayqUh2sF+/AYCHTQX3YqLfTQkgufyaQzSOzJ0tBAvh0MdgcYiDnUr3IwOEUcnUBJOwQamtZeCmwmmY0aGLFAimYoqp5SlcumIupmET5K6i6p4Gr4Xh37AelEQJ3ghm4K8f7S2UmAzwTRM1zDlVaOKdNqOAetVnnywrtWChy9MkQCYyqUhPprRN3IwM8k01HSIJge4JJw21twb5998KwW5EE3H/eZs9JmmNtxUNAX3+ZvX30tBzQS3YOpmCAxJo8uafGorLSrEGXmvZ3Oa9POMVmx7L2b4EpAYZykqnY8+vk8eRknv6LPhy/G99lBa7b16GPqifF+4WGW4FE6+PbozGMAoRaW23BPQCR5b2QgZ8Q+i1DUXCB6FzLAH8eqafQePQubeg3h1zcuzzhPfbTcFuzp+e+8iyruQh14ZuoUZtq5uRlO0Xw182jgkhtKTIIsucb86e4b/SCWbXlNsH56/P/tO+3B/+fbNm3cX+TIhXrNsZdWyWrlASvt3F9draAH8Q+SK9C+YaRcOhdb98uLyZjl3LTFOPyVxKVjltvoMNd3dgpiQO3AqT/C94AvfDWCKDb6rEi2BhRayv/H+9Rz938Xr81fo0evX58Wjb2FilLH1tK6ZzA04tD5s3TnMzx20knt2dubu4g2KzhH7vmPuDdurp4PvIuux/hRm9pyYfA7fzvHZgzksFSB8j+/emeunZ+/evH13/vabt98UF/G4vgWc9xaIzNAOkCn+9IPWfEacziomg89+wEdcgBnDv09mJ6urm7vrq8XV+ld9tf5yeXWr39xefrlerk7en/ztn+gyTtd/AjAH3m8NJwIzaL3EdmClWz5jj/MIvvnb34vHJIIAforXoSB2fvKu2FqZ5e/u10v9koSJRR5elXeFk56OklZf4ggSJHSEBTbJTjcp0gPboz5H9+qgkqFXrNP+TRwSL4vKWw/EeaSaJ8NJyBmyyie43uubJI5hld7E3us2NvUPz5g+7FCPfOcAq/sDctolsn8Hrd8VQfWKL1CGwwKXoMP/7x9OfkiL1PubG/zw1bPreNH79OmPDw/oerI4eK9ph8MhK/Cw7GtRhPaq0UdzgLISffkqLUk4WRwm5KFt4d+JOSe4c7zHM0/MtFDlrcZ8Z5o4RWC5FRF/esAVAp+UQA1NBOs3aoAI0Pw/0b819FFeQzJ1/oRNktKCCiOJ/5qNrRxGEvuQNa4Bi/yC3dT+2UsS+gi1ovrKX8wdq/KW3HtDUuqmERuOv6sJQJcI4UMLe8OzHLJm3fW6kToPOku+iJoCGl+0y8CRoG28dGzSPqyU7uK7BmTLdy3yUC3oFVb96LjK+Bq4qIcGX2Epb3rNztq9ZGe0DeD6w33+KPP/mJU9WGZNb4xZ3R9k1j2CmjW8K2ZtG8Sz2sb8jO5sS3mce6LO2nw9aS9qsiouibQXte/LHoO055nXHvXdefNdxS2L9mJPfVx2l6K8rrgrUd6XnNNmlUHnjOahUX9IUlEdTWb5Jvis5JU/q21Uz2pbx7PyZu6svMM6y7c9Z+XtyFljj3BG2bObVXfQZvmS3qy8mDarrGHNip2vWWlDapZvE83q2zezyn7KrLTyNGvcBMl5xc8gAemlMYPSlq7t4U1fuhGGM2nlthbOtNWLfPoTd1yMwpu4dG0Ja9I0OFj1YpCuxG33BnKkySPRsKdJL8xkT0C7xJIj9YA02bWO7CnyO/s4kuQ36vGkCYsejy1N722aDJIaN8+xp8mvYONIkl8lx5ym9wK/Lknt0Z37UzViDnMmKQdQ5k26q3SzXEnTIL8DkhWxd3kTZ3FxGdO1xDllTN0fqpZXUBZGtjsdJZwnVwL2TKXEPu1KwHkLEK+ojvuTWER13fkyJn12EwuXDMoNQGPSZ/fysMjou01gkIx6kH9OIdTrJgbJoN0AwSSo6waTwQKKa0U4RNDvtBksoLhohiJieKBREcLax61DgtRyiaHEHBmSvh4MZIgMWnC6MXJqkYDGiOocew8K0DhGTnu0xDFS60EMx8jqGKGPiKU3SlojwN1YaeW4c2NklUPCjZJTitY2Rk4eS22MkCLQ2Sgptfhj42TVQmyNEZZFwBolIw9PNURKx1RvZORmsRLzeMqjxDajEQ8Rl4dcGpK4EQppiJA8VNGgxHkkIZbUDMFpBIjJIvKIEkVYZS7gs5rL96wctmWWeWTPcne8We40Pctc4mYVb7RZycd5VvEHm1W8sGZVr+QZxRVqVnYenpU9emeViC+zLiebGf20G3x8sCNg+p4HzPgNNuqb+Zv5ay3f4ow0vCGfOamg4XYY2WSXPrXiGBFUZ4ABAuHwexfY/lheaIp3bgqQEhxcAVIiIRrBnA/jUUqhCU6R6yajiNqysmXh8aNRWyXllUOmIKh22PHLUBnpvs9QDjYA4N3rc708xuOWEYxKPtAA6VQ1S82alWQNKC8O2LPONRO8h6OZezvAtLIGh5UTm1S0z8dpKjbBlhEbUgQDt7rxIlBuZedDoFzyoWC5qMkwzUAOaSwc/pAglmzHipcbRFWHL8GyQzhs3CaeKUF6urQlhT1xBZJSAIlo90l0IUnNgV8LFI0aZ/vu5gtaQNiRvyw/hs8CN9GNwI4EttdtWI3cxi6iYnERhgVAgFeO9cg3Jcgv1wex0rNRNsl9wbLLBUuM6GLUQMy+SURV4GJEUUgWyTlbVi85zfob5D0HsUzHyPfHRqNht9uss0qiitetUPlo+wxWONuH8z8bCO4NUu/hNDtaoMZazApt5PGTbgSQX6nDyiX5kW06kJ/64uLzaP34QcUMOLhxl+ufJgHVby4W0wDf/fSreuCPJXcFhbBX5xMY+WZxpR7088XnS/Woq4sJVF3dTQD6ZXVxv54C9sMkoBOUJYgqqSlW0MUspTXnn6QVd2mNo7QGEHZd+vXF53ffvT2/kIMgrUGTlotfLm8u5IwRsWQ5nHFjKoe0vHZaWlvcdcZzPNTeCK2Dgc5/pg/IebBiw6I4IyYdszI/TDFFFYMGpgOsqpLwgTwNEVpFPYQmSrcAhPgkjOHkeEgzI3nWQ7AFIfBgoXnysYOtkPlpD7CJ3HD1JLDQaTvJWGhqbFjjl0gZYEzTVgKDjreT84kq0EI1thu/dcKEMn7nhwHGMpTYDGyTSEn9AWinXQmQt0cngy19a7sq8BTB7ALLNZQARYGSJsg+V1LA7XMl1dVW0pD6geGO35ZiAAoOSgr1b0BJUftNUZFGOMSPVwVa6EkfZGEYVQ1PZNm+uAXaTiAXKCnekZoeL3JtNXZTU4siVTjYw00dkr4HhlU4VUtFrLhvS0VKFLUOCCc71aAELzIEuGIxAD0Z4pYEOmAOSTje66QHJ194cN/qgdTSh5Y5KisAEpc5ss1xNItVAEMmSgqA0vZPAVLlbIBUJNwaKcLJWyMVeLg1EgUU+m628JsP+A3z0RY4oKRAoEem8yiuXWjDELja1AYhrmdoQRC7LtMGInRNpgVE5PpIC4TYtZEWkMA/oHCxxpP0bBE5+W6BEDojbsEQOT9tgcDn73RRJwiYwMS47/ZBlSI0SAMROnLvwBA+am/DcoIoQj2MMKAsYgM1UI/ofa4GWD6aJp6tJN6ObnvxVg5mZeuwiSlq8NGOWYssJBqwMxxKKQqJFMRG7BSsaOqlLHYgTtzBHfBEjnOnZ/DETTJp8q1IcJtFA0EnGqQCBI7AMkCTL5u/+CEKFSb0TRBFPoQCXiRwC5kGFoKd0IVHOkYM0/IcJR6EInCxkSYfPghU5Aiq6Dqaq0puUyT05xSUw8ESN5krA2RTd9xqyWjb80NLjiNXftGqyISR1QXmi1Cl6iEVp1Q9ZOIU1UMmCq4eogASz97awEKnErMRLnmlC12IoMCQgZZssMpotgwm2oB96+9SNGQBFXVqmxe79F6V7pXMruOPyfCDHQIHjq80Y79BUy8Qbg34Tcl1b6yFexAEhTjoQ8F2lImQRwmXIt2Xap3gMdbdnTtuaNKDgQ6typSPhMLKpOeOyuSWDJmIjuFlSxcClmdY0HCMQ3k1JQ+lKw8A+ang687woXoFMONXClqAskELWlpBBc99i47zy2iMaUi+NCQUGqoa8EsmhJ59JhGL9JqbRD5GOVCxBJRq5RECA8LQ80mIHfSXmIpChFYsQ6QLoby1Qxe38EmwCw0UPLj6gMRpUwglxGZ7P4pR7U6flzJa98xAR6/F6GSbbpDdUxcUNx6IlirEKGmnhMcPnNHEWORmuw+8odZ4ZKOygqnbovptyixTgmBcHvMGSAKA7ceodD8CQcPO6hQtvZ1K5MyiAoCcr2UWHM4AhOyCxRvkAGetQseNLr5HTXMNx4GtHwkzK6jvJi1Uxhw1VsLblibE+F38PuG4ou5IhNLanY1iANO+vG4wkXlSgmjXSQJguh0MYc0QWGhrxnDElrYGEG5W0zCj+fUuY7HCRlcpUm7ancEquUFRrrZwqgMOfiiWfKVLEyI43ofAsOB4JB09I/lu4sQ2ecFxZDnrUTTU3JWbPuZ61iqBZlYBQrl7p3ZZAwcD7QL5eqGqnHSAnFp/WP6lBa7N+qxCM9+LTWSlYxniuQNia8OsXbsQG/7vW2j3bwXJgqLGSopgveJwSG2Twjfua5Pywl6EWkQkHMv3uS8RiFEh0V1ymWqpMxYoakD1ZRBqeULFcQeIZpApXOCA9qZNat7yFKM63paiITIf9QgUpW+MyDZ1E4QxVB5djwNHGj5HNEp2iAFDJmbhsMlGV5z3SA5BRG6W1kr6RppxQPvVNkBXoBfP5/hShL6zVv0iAzhGQWZ9BC9Y5CPomT10iETRWrc2cCzYE2FhgwT9noQA2g0ObVx8a+1wUaaBfg5Pji0kQERm2yESgBEMTuu+wCHlox3Xi80YWWN0QfUFhKMMSkSMIoGH1+UaJUiUAFLWDj0dU+RRH4E3KDkE7GPX0fbAcXzYijk93mm1ZI6/6xuK1VIE2WXnvWurRUI/3uOu0ELX20Mhabrnb15/nzap6E/UhheHGtMnceknvgpGNyM8Jfs7fOj6VuKAh5P3Dyc/oKu2IIH3Nzf44atn1/Gi9+nTHx8eHk72cRy817TD4TAn+TWHfYEG52Z35KM5QIuk6MtXm8SG7ZeHk8VhQh7aFv6dmHOCOycbu3mHssI/8QWmOMTQzjRxusByK4L+9PDgvXr1g42iMCJDRq8CI0bzcPzV/D/RvzX00Q9aTak/YVOk5KDaSOK/Zv98OAmB6z8BCz7awg4QFB8tn3Goxwi++dvfi8fkisL86VHYcYE3sFMZd3Ce9wEmtv7XnkPtmR7YgKUSpthF/2vIoYb86ovkw4mRxD5krcERp5mHNw+PqRVNzCy9cuv+/WR2srq6ubu+Wlytf9VX6y+XV7f63eXN6uT9yQ9/hiZ4eHiFnN8g1I8PJ2fz1w8n8AnwTB8t6MFHX9YfT989nPwZYkLQFBN+4hku+JGm64JkQVVVJBSmDeB44GVlwv/CpJmsEywafgD//4et71ggLOSTDK18k30JZy3Fd8WdbjoigHph+DIlAWC+EAujh/iecPQEFzZizk7Z2bw+PSX2ZDgJmecKQ8iuoF3kHk4iyZMVWQdYJQ8qYfKbAUZFUm+5HE4KRBz6jlDhge3JsHgt1qmuCGYTe68V4ZzJwinO6slUhNxREtm/AxkwwHXsDfF5wHetjMT4QSNNbvmRTYKo3xnxHv5MQhtpFyeW7b/Peh0ta5iJrLw3wr9eyelZ1sBFHm1AVN+Sjhz6O5d6EbXxqrFJFs3gZ/lgoDB5Mx+4K0KBspeBgvoDyYpUIURqgUt0iJ7pK38xdyyBslGPtshXUkUbP59S66YRG46/Ew1A7lUv+SfIEy640Nh+eukxkS/c9A35svjbnh2PL/hDW+a8WVPWNHcuEw1unulLb9TWujFpyGov5euWNMTDofX7llRkmtiTqjUtbCOZkrYIcM2EI3mrrcI+rdll7e1goKw2G6GJ/AiBLWLzGw8FCO+CQFcpCoPIgCrNTus9jQ9Z84C+f6/97DuJCyLtPl+43tkxusMw2uOFeVTBWI7Rjbg5stmECrRD5W7MyXSvsBClL6UfmFpQreur3VapxPx10PHWrmtVv99TjVp1VOF6UW5FVaIZBVeKbo0bZZVp10Aeo5+AytrskzwxvWnD5vlN2dJtnd8JkSEKL0PVe+aVKFSFFK5R9fS3Eo2qkMI1KsUHVKJOCU9Km4UuHC6iACirRFVYOZpBPLU6pYDS+02VStVwpehWGbMr1a6BLFw/KL04O6VErwqiDH0UNxcVRBn6GFEEiMuoKn0KRFltxQR1qYIqfk5UnnSpUqsOKl4rciJKbQNRB5WklfukrvutIE429xmXmNn/ZIRMUYuajSbHe8IO/bYf4pPwuTeU5PwnN81ms+B2EpNPh6njbuSSrKqlJpZqQR5lHubCoE7FdgLDNBVdsdFo5iup2NjRQ349RhYprWalmOJ7pqqjjL9Be4EQz3QMcnxKkZa9PCZvsFSt35G8lt40YMvn0QIzzK9tpDA0WWPHmYSdFLb5Wrr9XWyztrhZXa1kbMNejifbKf+KeEvI3YElSugL2fPxLEppOZ81nDUaoaCl6moNRlJ3XjO0i89HpTyho0Lz5fqnY9I8paNIc/3mYnFk2meUVFng7qdfj80CKSUVFviIb3Y5Iv1zQiq0vzo/qtKf0lGh+c3i6pg0T+mo0PzzxefLY1I946NC99XFUeV6SkeJ5nfHpfmdMs2/rC7u18eke05IjfYfjkv3Dwo1P6p2LuOjSPejGtRnfP4dfUplrJQJ2LahFg/qaVdlJSRdXG+SmHyh8nhWRIQuftQUW04w2V0KmM3W1Pg0wVjmk4ABS02NCeZeAuZXNSUmmEYJmCrVlLj76Vf9+uLzu+/enl+o1qaOLVCtCSY7AiY0dSXU13XxVf3L5Y3ygpVhilRjipmUkNlSQxHlkyIBEx9aoZK329xeqMbuLNMKlWo9MtBjcOUobo8Xu+8pbbsdETadR5nHMbJcK2xT3FpcQpfi+YoAQHZp4zT65fByXHsN8zENEalevRK4tNwzQ5nnG/rKZijvkAOWL9PLvE83ef7muNhvk0imC3NfrcvgpSm4td3p1EvBpSm3CyzXmE69HF6agqV7xyfTsspBnqqHCQtqCi5Nud+iwJ5OuwxdmnrhVF17CVyacrGxcYAu/wBtj5oNGpIVln1kiUldeUeYcpzsIt6J1MzgpSmYTNpFJrJ7SASgH0IjCKbMxjoLeeo6QYQuKXicUNcyha/NFT0zbm3hAmabHexBaDipxkOdzFvkSznnYjq++agngZXekyC5ODRthM+E1FnICYoQygxM06NhiYAU5cjSy6Tq5RRkBUoI44kzsOAgRUXcj8sMpcagYsFBioq4K59UwYyBNPXyLnxyNctM5KgbGeQ6nQn1zChM7oyjYhuj0k/KH7xR7I4GcXUW0nrryTQsEZDYW0+qnry9GiN51kOwBSHwTKA/+U4s/xR8j8KdlKTksGFNXHxTApICp6lYiOyqm6a8tUjE0CCBtKfVscJDjqoq9uS6VJS3L2fGKvb5O3WTt9VvGRM3LikBOX2jot3Urr5R6o4q8PbohgJL0bZql541JlLUnVxLmcqp2jzuUE/uBvJOzaZjl34yNx7t84lb0pSAJOUm7gNTAnKUm3h4ZssblvmB4cqMH8igXU5BjiefEjeNDvVkumr8BiZuMFMCcpSbvDuQ6oeChKPbReKJF2eqPORsBCtxt+nQUarLzfTDslDqsCyybF9F/JcOBXMKkhR0wcSdRE5BjoJTLwBHEl31I9eeunSmDOSoN3UnKLMPjKbXTqp6ZA9/WgVzDhJV1PfAsNBe/hGoWuYi03ViUlULDvJcJyZVUKofpmIfzB41pfthEr+FafXMKEhR8MmwplUvJSBFuUMSqnBr79AuYyAvTLj7Vg8mbFGbPP5N3IQTDxoJWOjC0q/APzjPBpI3uiI305KRqkHjazT+R3h9UZWXXzHLeVCpkTUaMpqgyTUVqOMRtj1f5VGFvPyV2CtujlocUbuY/c9qoeoGUFd3+4YRFGbyxk5HprsaheVfjjhEb0EXKB5RI743QutghEBO071J4njkDU0tksV0Ct3lkLBX0CPUM0EjyNXuoGAjoOYJix0rp0dgyhf5TUNbvlTahYLNUeSLjG7eAdbXWoch9SkqMISt1t6Ux1EUkZbsUFF1kRkmqLcoOyqVNuVxFNlxRKOBCITIsmIHAd6T++ZrbT7IeE/fogtpdNuLtwoakzQTNGS3aiNCZSMsnnyLCRANfQ9HxRh2Uv2bVI6iAreUT4ntKTaEBbZGovI8XCVjUHPaQkN2iWxWgwl072ZzFOVSxlAwcgAI8Ob0V9ik59xxI0KyT1koiKwEFSzyxq2b11GUpZYMkzpmtGuWUVjNS5lEKjuNy1FkzDGNHl+iGLgOeALOVxLFeeOrmI6U7JJvuafIck50RsqCyNFUK8PLOa0TuMlEumXQck6yOEqaOIpaKbIcrSbLLKl5pTIOLlU5+UFwg9CH3CMfwgAvUhLCgKophYacgx5gp8gbm6ZmCV2SdjHkZitZOKfrV8KXo6ESV2yqbhIdsCFYMG0FrDGQ5nONt2AnG5HVGMhx1FUYLJWmo7BIqa0aHg6WCk9kmnIZ9LE5yUjxX8oHowoWLkq2ziLlZdDSxsHTqJUiyx4xTqRchYC0Hnga5aSGUi31f9NoV2MgvQeeSMsqA8k98DQ6VvDl9cDTKJdBf62+cVVblq6kk2zLUlx7fuNx68yfoD6iOdghcOCUnHtY05DkAtcPXwYOj2oZ5hqO45v6JtlugbTI15nqGmGuNUGl51+LKUEYev5gSwoes7Zt3WKSsrMGg1Q9B3LcY7jscux2Rs24RDc5c66aTdFUK4dTakpRtQSWCA/Ex15NIEXkSgBCD+0Hx4Ypa7iS5y+xS83dhspC4L23BFTH46LYduz4Ra2aFHDx2hFbIjvuQgOtf+p7w7McaTH9O3TtpCJW86IEmSGw0MKv4Ujvk9sKcY3Cv2EfQCnMkjuE1NapKxQFXGVNUq5rJxVJmk+k5Vfb1dumG4iZWaTmCNCdzZKbMERaq+ENtH67DpILUkOHASVIVCHY2qGLjwIkAayp1lDX9poxa1JxCyC7ZNQ1qT/ISQgpLlThkssNm4YTFqbhw/3uIAzSx0XNoBci2xWV43eiiZBBe6t7ueE4GzjZ0bchfHPwQ/mTr8ohDyr8VEU+3ofAsGAjLqrg21kknsSJbSJd2hG93MC5FloHgalMvPejWHfNRNiiBFJP6OTCPjx/f/adHvmm7pmBjgjLzrHMKOnzNgpf5cDU2G/IusrWGHzWTvZSFGph0WEEmAUoaBZsimTneMUq+ZZSk4PY2VXgGPHWDyfQrgYuRy09IzCpfhUWMtaZNsk0ClbQhSqGeqm8yZtCtwYBgerVK7Z/BI2LL6EWkuJBDkNMVzxz/H/Ddc/0bjt5kYJaDFy6V09EPCDKGR4jNvT4JQCyomb2KFbFF60cmYJOo1iOLVgp9+00ChFcwcr4ExU7X0ZxCx7hVGLnyvJL7lGpjC5YsSSaqhZlyIIVOtgRQB1yHsAlAnEi6/aqHhXbuYhW2jG8LIqA1FgOfQpTechQ1gJb25uqZ6szkDhsV64fhYAk9WQeMGZUUMghY0q0YMxoCtVK0F/lutbwsX33noLs7UqvsacwPAfa9hR8D7LzpN0jXVeGgipaIbQth81ly2/Ja1rVocWqpmZ2QgmCLl4VvIqeNzNKVWpCi1XN9mPUxT0C6cP6ilpVWLEq4TsaTd9RM++vBrRuQItVDV1BOU0b2EAWrFhsxIlijXJIsaqoL3XCCxumo2YAlypSQzymwztMn/Z81Pd6WADRZohQECNHB901PGPHGFpu5A4o3T1uY0S2KdhlOQ8dWFWy7JhNhWUvS126wJYdvVWqSBlTjBYmCGPIyDRiANs/OABUmi808JF6KeHPypOnURnrbdLl4CzRJsSLpAYm2zZ8E2K6ZUSOmtqsU3L5HjhUonO3PEWsU6CxfO1A2CCIgXQZbSxzhbSFccb4ColX8ca23yoos/IUMdJracI2kZXOd4cNykY1gdAE1kagpQtlSPjqTPzgsgAl2OSUpFSWJYyxVL+Fcr6VTjZHGV7L4CzLFFnLakQL+cMpilp9aqM4YJmpTvFFZNta5/cyriFNhFxr1kIuYb+kbIp58sY3wr47dShDbbQQMcHkmAQshowFjNCxnHxNJcyiIafCj3pEXjAdX2wrZiiCQqfCB9epXEq6g5+Eok5utRNuQo0ZW+Fr9qRZuQEwhqp9bkplWpE/hmhwcKUSrcgfQzSSnPeRqKwntzPI5VqDONauLNs64u3NkB2mWejFOSDllF9mC/wyW4jrgDv+xTlEXrxhstW4TPpRd/sdWTi+5lcNU95UosONabSIWIHriR3kRS0jYmnC3RjaiY9xW2hhL2qJq520kEUtXBclsjzmPox4vXLPxxj7oaatxZ2WJ8yzrob5TPywxUDWZrSpsGFZNpodkEBiYjwmUtXTIkZFYCpvDbKmG9mRQO/DKtGG9IEkBbbjNYK8bTdlZgQAePf6XFjTVyXYkD6QpLjdnho/zo2d9vZBNDPmUje0fW1/UW9LwkyB1hal2UoX+/B9q2A1kxoHFHPZhhYpb+bPA+DOzXDwEm6uglZmpvWD9di+lXsQ2k/ICeERvGBx6L/SuLeAcXOHwOHWBo4FR7RYkHjGNAg+nr8nIdA3hhPbLvIulsO0FYSLq2kgqRL4VQXzccJFRhavhvAB3LJSLINaSTYXM7R1AUJJVmsKH8BNjtUasrmYIen4+KF4YnXRfBbDq3flll+G6VpBRnCVlMttGFxM3RcLPD3acb0nFcu1A2UQWzkWpUgfkuvWDkmV08e1QXDxBEYggVpJahsb3mWDfez2L3tXVHP83XBfkUIxBKzlsriMuweO4x/80Bm8b1GjURXIxSUI/Sc7gpP2EUFJa2zqIkVltR/ve/3Sa9rZngWe54jVeN0wvFaVyK0a5QXtUV31HTAffcRHfzt/O39DMUJzTygN/MQxtxu0AjdiQSr2Xbt6QjuKE8v232vI8pkC9UWmPNWwef3Gjnkh0yRjVrL86JwWJIcBnJZ+EBO7JAo8xzos54/oxlM7imtHLftZ9coaZivgJS6vfbI0wxCNKAIhd4EoUg1dOBxUEsblP5yih/VGngG1SDUQ1YGFghs0SzRU08b6NpOmbGvWwxbuB+9UdNc1k1HHLKJcj6xRtYiPSynVqPLMiVqkGlOeeUGzRHKWfFuK3OJmdbXi7c8XfsgWELWR8soznYQrvHt9mQiXTbRybtdvlKDaGOunIcJaiq01RQzejyWi0OVwde89PjIlCYO5xL+jLaEYVtlBRKrJR1pkZzKM2VqtkaYezgEv29YCvTFTKCUezMANEt0I3afvBlGopJ74YMn9+nZ1Pmldh/0QqxUx2VphSpMPzko/0mPbfBxGoZRYtu/UCk9BhxsbUkV3hdq1O8x6VSW4WjX5sTqQDDz3TgIH6LZnDzxeNdYVskRA9+Cf/VmUnbcopcwGGjRhx+7Z1+DcWx1pBqjE76oKm7iZtX045gRG+0qM1OKVobMXqyxFVqbKEkb56qdy9DBmGED3scmkHHvpzq3HXKpzjTNflpIEYfYfzSaTMnHlIndgT1O1CDZua9jLM0mUTwyrIkaeh0CiHkHoAWckn0LIsVevsgGZy3Sqc3HKoyxCXB6M41MImbqKOQAEONLnRNUsx+co1XmaYgmmLGVEJtslUej6Ao5srpOiiTr6ClfYcYji+QJvWYqg3BhBqC7mWCc5wLXCJ94pDtPGnoziAkzfAv25gpUqL8bn6SZu+bwnl7bXKttsCBaFxzYSh6FTI9ZDaUj4h1ri4dEqoKBB6KNR9R3wQMgyEaTpXko8jgVT205jwNGSd6LrW8eI9oM5FMnHMXF8liUyGokspfQzlmNGGOUKk8Xed2zvkWW4UVIa9ejdogTkwiBCWUrZueDYm+G5ABNjsoubt3iPwODQFKbVKOmPtw/vt5So7WM4jzDroRpbzImsiMpMKckRHWDLWDG0Q0gRPIookgzY6k1T8/RFNWD2nkj+UR906ojdEyze26GlB0YYv/CW020IQBj7A0Pk4G0drkZk7E4JNe+L3aW2eoPsqZXMpGV6k52pbOekIoij/ecOSTx+f45qiEyrzo26PltkG2Z1YdyBmlu4uYHvt4/UuNnl4qTk15gOlqwIjakegR/GxsYZUi5qkj4tFqKuzb24v0Hd9keRlxIiRQdUXmJhLTOTBrXUMnpaJlPgXTdIpGuYoT+g+PZyzQV/lTfZ3AD3xhB15/keGIH+VkCBSFlphcBjCjffYkpbTGfQ46/da8SUhsbnwd1BCBbvBMW6HE+pLGkkKQsEIUDHXSxywxmOiNDui8pMsV3uSMLgCR0O20ELBAJo1qWNJPcRwiBflPHEypJGkur0aGYmxOPi3EHGBVFk7IC+SbbbjiVwZlpNeWMJBgm526YZ6WEYwYY8AQQPoREEIBREryxtJLms5xlPrCxpLKnQ/wdshARYqyxpJKnfEpAIMFMuZiSdCLjBXkB9LOSMJRSjSGZ4UCgg4+rSRpJbIXE3grjVhI22G3Z3EdW+NsSNpIeOcIxnlUkZSwbtnwrIwUKO1EUT+mhy8CyhLGHwYn9lADWYSl3KYDqdp116abAde+mAJ63xYPw8+XAPg0p1HUykIWb4URBYU0cUjDz5cAKkbg5nkKef2q8J7IZfdIZ9tJ5scBi1Wr389Gl5P3ZeTqTo9+s1e6YQ3bVCDY1I0arCxvbqWBh7d9DDSsQ4o1BPFKtM2HTLxQK3j6jBCKqrQEEwN4OAMZqCa8Qxsh0OqpAHhtDwzpgR+6GWi9PaIV3D9kRiFvI6QFGA5O9EopYEdsBeQCnoIDJM+xeO0HIVdPBsuIED3xR+bySseUGrCcPM6WYDrKF24WZWgHXwu8sSL/aGV3e8FcmNBsTBCzeq0gzXisbCcOkhlzv2G7cHkysB8fBSYLYKFAu3G3JZmHyblYB4eCmwWQWKhdtdGppavtHKSDzMfj5TYbg6GhfDc6UMz9kZrmA/B8uD/MwtAXHw+kRx5ZFJ7xPd/6fPegoytwLFwW2RRLHvKmRYBuTgeZn6P6sjWkHsYPrBiMC3b4cVQeSdh730kgAt5muFrH7AgZZogezV8gUO4tb+TyhUmhDYijw2YFEa1yR2gC9+urq79nc7nlB6ndgOEabVBHdQWIPn+NZzXrKvBRkhI0IV30FnhavNAl9ONtwk9VpYl8pKYIQxOin0WUFAZtTxWTMA1dc378jQdngGRCBOAj0wXhzfsLS6TFb4Eep3EGCplHep9W6A64cDJ9X1KkGX27Wg8BKh+4RQqPRkEwnvmmjiO9gYoLqEy0ygvDLmwtl57ERaCAIfGSc0whctldyFHXlnUEAEZDEoy+/hcQjtWCaPXH4Hj03aqUohUQjvYmDvUBhFSQxy4R0MTFMWfCq5C9sO9rXNHYHwufBeBthvRCqNHKGLS3r3jI42amSxqWN08YlD3Qo3O1lUSuI7WADT2ktikInuRo8MefBEdie+rHKZSu7G1s0kfJLWYVUBuph4cegH7FeGcdIopHdw2D9aW0kEMtFd6K5hyqyMFfldO0Ls12DzEXAbV2DXXd+ArH4qldyF/WhG38hCz2R34adDTlkUSuK7xtF74/ybbyVxKIR3M/jm7Fweg1R4B4Pnb15/Lwk/E92DrpshMKSNnGsInb2DOZ5DOoUi7/Vshpd+nhGMbe/FDF8CEmsvxe1mposYMwwjpzOMKeBHIkYVQwn2jzrC0BcwLB/CL0PuYOfbAjqhAdxS3M5+YhJiQSPKQIOXoBnOIHIsc5/gUdC6xCCGLGsWwaOgFYtBDFlWM7JuHN90OQ3POoP+viyehGgZvIcjtrxuRtO0hw0GXaOjGKIkQRb/5H519gz/kUw7vc7ePjx/f/ad9uH+8u2bN+8u8sVavIbcyqtn9XiBzODfXVyvoU3wD7E7Cb9gzl1IHQTvlxeXN8u5a4lyUysJrMCmrvl3RrwXAiRSfLYoLkNmPcNEYuCgLkLFtRUv0TD5kWJxYn///Xc9LR3AQn6hp1ncOnEY5fbEc8gFJGTmIUGhKpjtKwHibNxxNB45TGgTOyVYEixc2/yTXGknKRs9Pej4gtJ+QXoWlXMTWXrkm49ALhwJEZ/vm2K9XTPRrNBGd7WkQXvIr/Q6hEvy40pIyRLEzMTOB0fBRXrJ8EB88EN03hT7m05aPELfzbJgChoosphm7u1AKvrGN0IrA5/S2gEI8c6l4ejZo+msPk2NS7Gz6LiTZUXiwUTA0o3APgoeR1I0Muw9rDEHIwQ5mU0SxxNnWd5+pmFZlRI52CGAE6gIraZ6/nTwtunW59CKkLd26OIikQS70Jhw4NAomw6cYk2XIVMBR47uTTC4zPGN/Ua3PTja3hroZpUjaBiqgfCno4PP1jrgicSAkMYjSA+14JfikejX3svCQJeQy5Kd3rUuKRu4BjM9N/cOldC8m3GcpMrlgENFtVxsNlRc/WKF4XLS0MacAhhjrwqTWo0iI1osNdLm2JwuX681Lps5xniDwh2M1bS45Gi0pK5OC4ekuswjJD5UtnL01a+r9RLm3O3nj1ef9C+rpb66XfxluV7h7ZMnw0nQp2esMi+XH7580pcfb1gT3HxYXq6vVxmBj1fXywryw8P/+S3x4/+brsOdoon+ab5ce2pmZ17Sz1hhP/9880a/hprqtz8v7++vLpfD9L29W1/dXP2/pb6++vzr4v7Xu7V+sWJWfnV1ffFhpd/d3/58tbq6/Yz+Wt8ubq/1n88qfF4zS7zWM4uivMxZDdMOSiu4LX66+Px5ea0vP198uF5eCpD4afl5eX+xvr0fJqsw+d09zIT11c/LFbvlf/kEi9PN2dnZzaf1hwt2/lf66grvHw1TP03+4fU4AX/VbxZf0qzQP15frH7SP1yslpf68q/LxZc1tK4I+YvbmxuYT0T+ze3QSlIXimv6/cXl1a3+4fbi/hJT139eDiwHveKh5PPBxZWI+HxxU1WeNDfZrgBf45NLvV/+TBF68fqcW97n5Rrl1t3t5+XntX71eXH95RLVUTYBur5aX6yvFjDh9dXnqqI49IgJH9ieY3v1MUQXJ5InRNOrz1dr5qT3Fze4SFSbwOfX5pdrLhkr2DDXZJxvzdevOcTQqtvV3c0X/eLuir2xyWyBq76OqN3kfe6ofhYTGiPhy8X9wL4hNQYRA9uGL0OJkNbl7uLTMs0w3qy5/fjx+vbiEtWBX27v/4LK8uIv7B1B0xmAATPV/pajDJRL0tXn9fL+48WCWdv1BbT0Eg7XrtG/y+3ygJ6L3TJ/1e+uL9Yfb+9vBrafpNj/urpfL2AvvVzB1mlwS0x0h+OtxtC7o2H7ZXnxlwqirhtxHNqbJAa6/oc/HIDx+Mc/crD45erj1YimlqVHef36XHSP8i2fPDKs/vwFtqGXf9HXPyEfKDRcvoC5AMdrqK7e3eJCXJ0nnHMQLmy4uFhfXN9+KgoIm4z79RoPcvGA+2HIYDkPV6evlovGoImYrPiIasLUj+NjxQdtZ9YnYdTPPB9OAVk+jGLL/K//6vySbTbMcDEYnQGTPm7to9j3ndsgtTn6cWXBr4qn88Sco0UwKCTElvfx446v5ugL1/4dR0OrZJYFNkl9J1ICvvn8rKODmpYRWhV8mD+NppUFH/0y94btdRPIP5ubQVIF9sMYPJ+6b1WAb2vg2+Dp7WlU30ySA+34RqwbG7s6OvW38XYIPrmFsBs8vamQ/GdlhnYQV8D/AwVrB2asGUns74CnkS/RErC+8hdzp+4yKqFAbhPPRA/1COD/RhWGcZjUR+wSOFhGbAjF58gcz/B83dRhezSF5r5rx/o2hM2fHvh4I2sCEtAA4NkEwVTZD/HDOLYVZ3zmGXtjBLgXUq+32dITfP+9fOyDEXq2t4vmhuNMoHoOD57j0JiSQAAsw0MLFJVuyXAilSSQIwE+IRcNpOEajwB1G1CSO0eDstgIdyCu82j5rDEmOHXhkx/5RgYjKcT7xN3USKTP5IPXhyWnLnzyYzo4ObXOvlVCgjpAgVTQ81P4/EeOwUoDpGh1evkUn7Y1UadwQvEjazvVIT899MNGBsW1bhs9E0LMQ2jBlGgd2OnW80/J00kItfTomFb5nbqylLV2er3LOf0FP1FrJrlsBtml2Ree/pI+m8g20hjx2Kd1yn56yzZhF2gZmVx4bNI+YzrdonenxTu1BlJGjMda3XPc0232fjKrKSfIVf+656inW/TBKf7gNP9AcbVURZE+v2z5rH3hZ9x6z0hWeMWjsd5xCke6wIx+RG/n+E8VXLJJuE5+664RVFn9NZX38OoUTtR//I8/3H5Z331Z65dX93/U/uMPd/e3/71crNFeyB/nOPGYgtdgbUcm5S4hLPbajuJcdNE7wtFV4iURsE4DAxW3RknrFdE19epN3JOJvenrnZhWWJDDrns/iv9nGZbPUNAsc+K5PbctAP98c07MZcVzciDP2iS2Y+HV6/nOS+al9g6FH63bsySw9jX5aI4MPscuyOgCuX8r0/emp9661fH9Nr2w99QB3i7e/1jfDpSd1WgOx5PZ5e//N7unzW6yf4qzOt3bqede6ojuB9X5Q2Qfdt+ffeeenZ25u3gzcILV0vlyt7YJ/KEHIRwobXW8/MRp01+c2enpzmwZrrIlh8UQzUNPw8MzlLNz0TkHsb2TImvJ7xvSwRRTz4C+zZoJx9o6xi6aoGyIztxhzSyH3dKvM8v9u9it0YKgCC7uRsiQ7Rn+yMWdHux4f9qMvXQkdYNXnGmHZuIYoQUC4FnAM1+G7WEdj0YebBWtxqyQfQdqTA0UoEZRmzmy5gct7aTxr1c//PnZddCnIESRteDHZ3PiZg/QzRi2t4OPvqw/nr57OPkzEZB18rkLU2LOXd9KYI3CN2zMF/io2B357A7a+AMmngftmmNXL5geSgpAGL+sTPhfKCgfPpRNH0ABWPNVDII/QfqV34pUssjFTCsQx3jzkkMXTR6rMSaWSCsxU2JDs7x+w3G6dERriqtx7OZmaOrp8SYzJIiorMBMy6sBfJQHCKM3W+Xba6tl62R2srq6ubu+Wlytf9VX6y/ovMTd/e3d8n59tVydvD/558NJKTjd+wf44AGOdI0nAMurbz7+bIQ2Ov4Xocfv0b/QB+gf2AIENvzKerz2TbLYnr54n/2xA+ajj47B6m/nb+dvssez7A909O42aKZrDLTT5/8i/4ICTtKbx74ayv+CWUHQkSNLBC3/t8L0wIKSUMbO8gKGzwUi5TqWIeHXfmjvbM9w0s+9xHHg07RywAdnM+znG8MxCPr17fffn707/+7t63/9/eRf/x+pRz/f=END_SIMPLICITY_STUDIO_METADATA
