/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace TlsCertificateManagement {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 9;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 6;

namespace ProvisionRootCertificate {
inline constexpr CommandId Id = 0x00000000;
} // namespace ProvisionRootCertificate

namespace ProvisionRootCertificateResponse {
inline constexpr CommandId Id = 0x00000001;
} // namespace ProvisionRootCertificateResponse

namespace FindRootCertificate {
inline constexpr CommandId Id = 0x00000002;
} // namespace FindRootCertificate

namespace FindRootCertificateResponse {
inline constexpr CommandId Id = 0x00000003;
} // namespace FindRootCertificateResponse

namespace LookupRootCertificate {
inline constexpr CommandId Id = 0x00000004;
} // namespace LookupRootCertificate

namespace LookupRootCertificateResponse {
inline constexpr CommandId Id = 0x00000005;
} // namespace LookupRootCertificateResponse

namespace RemoveRootCertificate {
inline constexpr CommandId Id = 0x00000006;
} // namespace RemoveRootCertificate

namespace ClientCSR {
inline constexpr CommandId Id = 0x00000007;
} // namespace ClientCSR

namespace ClientCSRResponse {
inline constexpr CommandId Id = 0x00000008;
} // namespace ClientCSRResponse

namespace ProvisionClientCertificate {
inline constexpr CommandId Id = 0x00000009;
} // namespace ProvisionClientCertificate

namespace FindClientCertificate {
inline constexpr CommandId Id = 0x0000000A;
} // namespace FindClientCertificate

namespace FindClientCertificateResponse {
inline constexpr CommandId Id = 0x0000000B;
} // namespace FindClientCertificateResponse

namespace LookupClientCertificate {
inline constexpr CommandId Id = 0x0000000C;
} // namespace LookupClientCertificate

namespace LookupClientCertificateResponse {
inline constexpr CommandId Id = 0x0000000D;
} // namespace LookupClientCertificateResponse

namespace RemoveClientCertificate {
inline constexpr CommandId Id = 0x0000000E;
} // namespace RemoveClientCertificate

} // Commands
} // TlsCertificateManagement
} // Clusters
} // app
} // chip
