/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <clusters/shared/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace PumpConfigurationAndControl {
namespace Attributes {

// Total number of attributes supported by the cluster, including global attributes
inline constexpr uint32_t kAttributesCount = 28;

namespace MaxPressure {
inline constexpr AttributeId Id = 0x00000000;
} // namespace MaxPressure


namespace MaxSpeed {
inline constexpr AttributeId Id = 0x00000001;
} // namespace MaxSpeed


namespace MaxFlow {
inline constexpr AttributeId Id = 0x00000002;
} // namespace MaxFlow


namespace MinConstPressure {
inline constexpr AttributeId Id = 0x00000003;
} // namespace MinConstPressure


namespace MaxConstPressure {
inline constexpr AttributeId Id = 0x00000004;
} // namespace MaxConstPressure


namespace MinCompPressure {
inline constexpr AttributeId Id = 0x00000005;
} // namespace MinCompPressure


namespace MaxCompPressure {
inline constexpr AttributeId Id = 0x00000006;
} // namespace MaxCompPressure


namespace MinConstSpeed {
inline constexpr AttributeId Id = 0x00000007;
} // namespace MinConstSpeed


namespace MaxConstSpeed {
inline constexpr AttributeId Id = 0x00000008;
} // namespace MaxConstSpeed


namespace MinConstFlow {
inline constexpr AttributeId Id = 0x00000009;
} // namespace MinConstFlow


namespace MaxConstFlow {
inline constexpr AttributeId Id = 0x0000000A;
} // namespace MaxConstFlow


namespace MinConstTemp {
inline constexpr AttributeId Id = 0x0000000B;
} // namespace MinConstTemp


namespace MaxConstTemp {
inline constexpr AttributeId Id = 0x0000000C;
} // namespace MaxConstTemp


namespace PumpStatus {
inline constexpr AttributeId Id = 0x00000010;
} // namespace PumpStatus


namespace EffectiveOperationMode {
inline constexpr AttributeId Id = 0x00000011;
} // namespace EffectiveOperationMode


namespace EffectiveControlMode {
inline constexpr AttributeId Id = 0x00000012;
} // namespace EffectiveControlMode


namespace Capacity {
inline constexpr AttributeId Id = 0x00000013;
} // namespace Capacity


namespace Speed {
inline constexpr AttributeId Id = 0x00000014;
} // namespace Speed


namespace LifetimeRunningHours {
inline constexpr AttributeId Id = 0x00000015;
} // namespace LifetimeRunningHours


namespace Power {
inline constexpr AttributeId Id = 0x00000016;
} // namespace Power


namespace LifetimeEnergyConsumed {
inline constexpr AttributeId Id = 0x00000017;
} // namespace LifetimeEnergyConsumed


namespace OperationMode {
inline constexpr AttributeId Id = 0x00000020;
} // namespace OperationMode


namespace ControlMode {
inline constexpr AttributeId Id = 0x00000021;
} // namespace ControlMode


namespace GeneratedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::GeneratedCommandList::Id;
} // namespace GeneratedCommandList


namespace AcceptedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::AcceptedCommandList::Id;
} // namespace AcceptedCommandList


namespace AttributeList {
inline constexpr AttributeId Id = Globals::Attributes::AttributeList::Id;
} // namespace AttributeList


namespace FeatureMap {
inline constexpr AttributeId Id = Globals::Attributes::FeatureMap::Id;
} // namespace FeatureMap


namespace ClusterRevision {
inline constexpr AttributeId Id = Globals::Attributes::ClusterRevision::Id;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace PumpConfigurationAndControl
} // namespace Clusters
} // namespace app
} // namespace chip
