/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace CameraAvSettingsUserLevelManagement {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 7;


namespace MPTZSetPosition {
inline constexpr CommandId Id = 0x00000000;
} // namespace MPTZSetPosition

namespace MPTZRelativeMove {
inline constexpr CommandId Id = 0x00000001;
} // namespace MPTZRelativeMove

namespace MPTZMoveToPreset {
inline constexpr CommandId Id = 0x00000002;
} // namespace MPTZMoveToPreset

namespace MPTZSavePreset {
inline constexpr CommandId Id = 0x00000003;
} // namespace MPTZSavePreset

namespace MPTZRemovePreset {
inline constexpr CommandId Id = 0x00000004;
} // namespace MPTZRemovePreset

namespace DPTZSetViewport {
inline constexpr CommandId Id = 0x00000005;
} // namespace DPTZSetViewport

namespace DPTZRelativeMove {
inline constexpr CommandId Id = 0x00000006;
} // namespace DPTZRelativeMove

} // Commands
} // CameraAvSettingsUserLevelManagement
} // Clusters
} // app
} // chip
