/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/CameraAvSettingsUserLevelManagement/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace CameraAvSettingsUserLevelManagement {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace MPTZPosition{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MPTZPosition::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MPTZPosition
namespace MaxPresets{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxPresets::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxPresets
namespace MPTZPresets{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MPTZPresets::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MPTZPresets
namespace DPTZStreams{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DPTZStreams::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace DPTZStreams
namespace ZoomMax{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ZoomMax::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ZoomMax
namespace TiltMin{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TiltMin::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TiltMin
namespace TiltMax{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TiltMax::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TiltMax
namespace PanMin{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PanMin::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PanMin
namespace PanMax{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PanMax::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PanMax
namespace MovementState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MovementState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MovementState

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {
namespace MPTZSetPosition {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    MPTZSetPosition::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace MPTZSetPosition
namespace MPTZRelativeMove {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    MPTZRelativeMove::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace MPTZRelativeMove
namespace MPTZMoveToPreset {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    MPTZMoveToPreset::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace MPTZMoveToPreset
namespace MPTZSavePreset {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    MPTZSavePreset::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace MPTZSavePreset
namespace MPTZRemovePreset {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    MPTZRemovePreset::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace MPTZRemovePreset
namespace DPTZSetViewport {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    DPTZSetViewport::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace DPTZSetViewport
namespace DPTZRelativeMove {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    DPTZRelativeMove::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace DPTZRelativeMove

} // namespace Commands
} // namespace CameraAvSettingsUserLevelManagement
} // namespace Clusters
} // namespace app
} // namespace chip
