/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace CameraAvStreamManagement {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 10;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 4;

namespace AudioStreamAllocate {
inline constexpr CommandId Id = 0x00000000;
} // namespace AudioStreamAllocate

namespace AudioStreamAllocateResponse {
inline constexpr CommandId Id = 0x00000001;
} // namespace AudioStreamAllocateResponse

namespace AudioStreamDeallocate {
inline constexpr CommandId Id = 0x00000002;
} // namespace AudioStreamDeallocate

namespace VideoStreamAllocate {
inline constexpr CommandId Id = 0x00000003;
} // namespace VideoStreamAllocate

namespace VideoStreamAllocateResponse {
inline constexpr CommandId Id = 0x00000004;
} // namespace VideoStreamAllocateResponse

namespace VideoStreamModify {
inline constexpr CommandId Id = 0x00000005;
} // namespace VideoStreamModify

namespace VideoStreamDeallocate {
inline constexpr CommandId Id = 0x00000006;
} // namespace VideoStreamDeallocate

namespace SnapshotStreamAllocate {
inline constexpr CommandId Id = 0x00000007;
} // namespace SnapshotStreamAllocate

namespace SnapshotStreamAllocateResponse {
inline constexpr CommandId Id = 0x00000008;
} // namespace SnapshotStreamAllocateResponse

namespace SnapshotStreamModify {
inline constexpr CommandId Id = 0x00000009;
} // namespace SnapshotStreamModify

namespace SnapshotStreamDeallocate {
inline constexpr CommandId Id = 0x0000000A;
} // namespace SnapshotStreamDeallocate

namespace SetStreamPriorities {
inline constexpr CommandId Id = 0x0000000B;
} // namespace SetStreamPriorities

namespace CaptureSnapshot {
inline constexpr CommandId Id = 0x0000000C;
} // namespace CaptureSnapshot

namespace CaptureSnapshotResponse {
inline constexpr CommandId Id = 0x0000000D;
} // namespace CaptureSnapshotResponse

} // Commands
} // CameraAvStreamManagement
} // Clusters
} // app
} // chip
