/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Identify/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Identify {

inline constexpr uint32_t kRevision = 6;

namespace Attributes {
namespace IdentifyTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    IdentifyTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace IdentifyTime
namespace IdentifyType{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    IdentifyType::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace IdentifyType

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    IdentifyTime::kMetadataEntry,
    IdentifyType::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace Identify {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Identify::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace Identify
namespace TriggerEffect {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    TriggerEffect::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace TriggerEffect

} // namespace Commands
} // namespace Identify
} // namespace Clusters
} // namespace app
} // namespace chip
