/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/CommodityPrice/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace CommodityPrice {

inline constexpr uint32_t kRevision = 4;

namespace Attributes {
namespace TariffUnit{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TariffUnit::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TariffUnit
namespace Currency{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Currency::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Currency
namespace CurrentPrice{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentPrice::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentPrice
namespace PriceForecast{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PriceForecast::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PriceForecast

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    TariffUnit::kMetadataEntry,
    Currency::kMetadataEntry,
    CurrentPrice::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace GetDetailedPriceRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GetDetailedPriceRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace GetDetailedPriceRequest
namespace GetDetailedForecastRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GetDetailedForecastRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace GetDetailedForecastRequest

} // namespace Commands
} // namespace CommodityPrice
} // namespace Clusters
} // namespace app
} // namespace chip
