/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <clusters/shared/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace CommodityTariff {
namespace Attributes {

// Total number of attributes supported by the cluster, including global attributes
inline constexpr uint32_t kAttributesCount = 24;

namespace TariffInfo {
inline constexpr AttributeId Id = 0x00000000;
} // namespace TariffInfo


namespace TariffUnit {
inline constexpr AttributeId Id = 0x00000001;
} // namespace TariffUnit


namespace StartDate {
inline constexpr AttributeId Id = 0x00000002;
} // namespace StartDate


namespace DayEntries {
inline constexpr AttributeId Id = 0x00000003;
} // namespace DayEntries


namespace DayPatterns {
inline constexpr AttributeId Id = 0x00000004;
} // namespace DayPatterns


namespace CalendarPeriods {
inline constexpr AttributeId Id = 0x00000005;
} // namespace CalendarPeriods


namespace IndividualDays {
inline constexpr AttributeId Id = 0x00000006;
} // namespace IndividualDays


namespace CurrentDay {
inline constexpr AttributeId Id = 0x00000007;
} // namespace CurrentDay


namespace NextDay {
inline constexpr AttributeId Id = 0x00000008;
} // namespace NextDay


namespace CurrentDayEntry {
inline constexpr AttributeId Id = 0x00000009;
} // namespace CurrentDayEntry


namespace CurrentDayEntryDate {
inline constexpr AttributeId Id = 0x0000000A;
} // namespace CurrentDayEntryDate


namespace NextDayEntry {
inline constexpr AttributeId Id = 0x0000000B;
} // namespace NextDayEntry


namespace NextDayEntryDate {
inline constexpr AttributeId Id = 0x0000000C;
} // namespace NextDayEntryDate


namespace TariffComponents {
inline constexpr AttributeId Id = 0x0000000D;
} // namespace TariffComponents


namespace TariffPeriods {
inline constexpr AttributeId Id = 0x0000000E;
} // namespace TariffPeriods


namespace CurrentTariffComponents {
inline constexpr AttributeId Id = 0x0000000F;
} // namespace CurrentTariffComponents


namespace NextTariffComponents {
inline constexpr AttributeId Id = 0x00000010;
} // namespace NextTariffComponents


namespace DefaultRandomizationOffset {
inline constexpr AttributeId Id = 0x00000011;
} // namespace DefaultRandomizationOffset


namespace DefaultRandomizationType {
inline constexpr AttributeId Id = 0x00000012;
} // namespace DefaultRandomizationType


namespace GeneratedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::GeneratedCommandList::Id;
} // namespace GeneratedCommandList


namespace AcceptedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::AcceptedCommandList::Id;
} // namespace AcceptedCommandList


namespace AttributeList {
inline constexpr AttributeId Id = Globals::Attributes::AttributeList::Id;
} // namespace AttributeList


namespace FeatureMap {
inline constexpr AttributeId Id = Globals::Attributes::FeatureMap::Id;
} // namespace FeatureMap


namespace ClusterRevision {
inline constexpr AttributeId Id = Globals::Attributes::ClusterRevision::Id;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace CommodityTariff
} // namespace Clusters
} // namespace app
} // namespace chip
