/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/WiFiNetworkManagement/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace WiFiNetworkManagement {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace Ssid{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Ssid::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Ssid
namespace PassphraseSurrogate{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PassphraseSurrogate::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kManage,
    std::nullopt
);
} // namespace PassphraseSurrogate

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    Ssid::kMetadataEntry,
    PassphraseSurrogate::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace NetworkPassphraseRequest {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    NetworkPassphraseRequest::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace NetworkPassphraseRequest

} // namespace Commands
} // namespace WiFiNetworkManagement
} // namespace Clusters
} // namespace app
} // namespace chip
