/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ScenesManagement {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 8;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 7;

namespace AddScene {
inline constexpr CommandId Id = 0x00000000;
} // namespace AddScene

namespace AddSceneResponse {
inline constexpr CommandId Id = 0x00000000;
} // namespace AddSceneResponse

namespace ViewScene {
inline constexpr CommandId Id = 0x00000001;
} // namespace ViewScene

namespace ViewSceneResponse {
inline constexpr CommandId Id = 0x00000001;
} // namespace ViewSceneResponse

namespace RemoveScene {
inline constexpr CommandId Id = 0x00000002;
} // namespace RemoveScene

namespace RemoveSceneResponse {
inline constexpr CommandId Id = 0x00000002;
} // namespace RemoveSceneResponse

namespace RemoveAllScenes {
inline constexpr CommandId Id = 0x00000003;
} // namespace RemoveAllScenes

namespace RemoveAllScenesResponse {
inline constexpr CommandId Id = 0x00000003;
} // namespace RemoveAllScenesResponse

namespace StoreScene {
inline constexpr CommandId Id = 0x00000004;
} // namespace StoreScene

namespace StoreSceneResponse {
inline constexpr CommandId Id = 0x00000004;
} // namespace StoreSceneResponse

namespace RecallScene {
inline constexpr CommandId Id = 0x00000005;
} // namespace RecallScene

namespace GetSceneMembership {
inline constexpr CommandId Id = 0x00000006;
} // namespace GetSceneMembership

namespace GetSceneMembershipResponse {
inline constexpr CommandId Id = 0x00000006;
} // namespace GetSceneMembershipResponse

namespace CopyScene {
inline constexpr CommandId Id = 0x00000040;
} // namespace CopyScene

namespace CopySceneResponse {
inline constexpr CommandId Id = 0x00000040;
} // namespace CopySceneResponse

} // Commands
} // ScenesManagement
} // Clusters
} // app
} // chip
