/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/ScenesManagement/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ScenesManagement {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace SceneTableSize{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SceneTableSize::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SceneTableSize
namespace FabricSceneInfo{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    FabricSceneInfo::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace FabricSceneInfo

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    SceneTableSize::kMetadataEntry,
    FabricSceneInfo::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace AddScene {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AddScene::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace AddScene
namespace ViewScene {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ViewScene::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace ViewScene
namespace RemoveScene {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RemoveScene::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace RemoveScene
namespace RemoveAllScenes {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RemoveAllScenes::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace RemoveAllScenes
namespace StoreScene {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    StoreScene::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace StoreScene
namespace RecallScene {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RecallScene::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace RecallScene
namespace GetSceneMembership {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GetSceneMembership::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace GetSceneMembership
namespace CopyScene {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    CopyScene::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kManage
);
} // namespace CopyScene

} // namespace Commands
} // namespace ScenesManagement
} // namespace Clusters
} // namespace app
} // namespace chip
