/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/GroupKeyManagement/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace GroupKeyManagement {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace GroupKeyMap{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    GroupKeyMap::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace GroupKeyMap
namespace GroupTable{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    GroupTable::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace GroupTable
namespace MaxGroupsPerFabric{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxGroupsPerFabric::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxGroupsPerFabric
namespace MaxGroupKeysPerFabric{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxGroupKeysPerFabric::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxGroupKeysPerFabric

constexpr std::array<DataModel::AttributeEntry, 4> kMandatoryMetadata = {
    GroupKeyMap::kMetadataEntry,
    GroupTable::kMetadataEntry,
    MaxGroupsPerFabric::kMetadataEntry,
    MaxGroupKeysPerFabric::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace KeySetWrite {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    KeySetWrite::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kAdminister
);
} // namespace KeySetWrite
namespace KeySetRead {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    KeySetRead::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kAdminister
);
} // namespace KeySetRead
namespace KeySetRemove {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    KeySetRemove::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kAdminister
);
} // namespace KeySetRemove
namespace KeySetReadAllIndices {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    KeySetReadAllIndices::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kAdminister
);
} // namespace KeySetReadAllIndices

} // namespace Commands
} // namespace GroupKeyManagement
} // namespace Clusters
} // namespace app
} // namespace chip
