/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/MediaInput/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace MediaInput {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace InputList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    InputList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace InputList
namespace CurrentInput{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentInput::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentInput

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    InputList::kMetadataEntry,
    CurrentInput::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SelectInput {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SelectInput::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SelectInput
namespace ShowInputStatus {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ShowInputStatus::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace ShowInputStatus
namespace HideInputStatus {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    HideInputStatus::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace HideInputStatus
namespace RenameInput {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RenameInput::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace RenameInput

} // namespace Commands
} // namespace MediaInput
} // namespace Clusters
} // namespace app
} // namespace chip
