pipeline {
    agent any
    stages {
        stage('Trigger downstream') {
            steps {
                build job: 'Matter GitHub Jenkins/feature%20github_integration', parameters:[string(name: 'branchName', value: env.BRANCH_NAME), string(name:'buildNumber', value: env.BUILD_NUMBER)]
            }
        }
    }
}