pipeline {
    agent any
    stages {
    //trigger build 2
        stage('Trigger downstream') {
            steps {
                script {
                    def encodedBranchName = env.BRANCH_NAME.replace("/", "%2F")
                    build job: "Matter GitHub Jenkins/${encodedBranchName}", parameters:[string(name: 'branchName', value: env.BRANCH_NAME), string(name:'buildNumber', value: env.BUILD_NUMBER)], wait: false
                }
            }
        }
    }
}