pipeline {
    agent any
    stages {
    // Trigger4
        stage('Trigger downstream') {
            steps {
                build job: 'Matter GitHub Jenkins/feature%2Fgithub_integration', parameters:[string(name: 'branchName', value: env.BRANCH_NAME), string(name:'buildNumber', value: env.BUILD_NUMBER)], wait: false
            }
        }
    }
}