/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/AccessControl/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace AccessControl {

inline constexpr uint32_t kRevision = 3;

namespace Attributes {
namespace Acl{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Acl::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kAdminister,
    Access::Privilege::kAdminister
);
} // namespace Acl
namespace Extension{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Extension::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kAdminister,
    Access::Privilege::kAdminister
);
} // namespace Extension
namespace SubjectsPerAccessControlEntry{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SubjectsPerAccessControlEntry::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SubjectsPerAccessControlEntry
namespace TargetsPerAccessControlEntry{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TargetsPerAccessControlEntry::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TargetsPerAccessControlEntry
namespace AccessControlEntriesPerFabric{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AccessControlEntriesPerFabric::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AccessControlEntriesPerFabric
namespace CommissioningARL{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CommissioningARL::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CommissioningARL
namespace Arl{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Arl::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Arl
namespace AuxiliaryACL{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AuxiliaryACL::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kAdminister,
    std::nullopt
);
} // namespace AuxiliaryACL

constexpr std::array<DataModel::AttributeEntry, 4> kMandatoryMetadata = {
    Acl::kMetadataEntry,
    SubjectsPerAccessControlEntry::kMetadataEntry,
    TargetsPerAccessControlEntry::kMetadataEntry,
    AccessControlEntriesPerFabric::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace ReviewFabricRestrictions {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ReviewFabricRestrictions::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kAdminister
);
} // namespace ReviewFabricRestrictions

} // namespace Commands
} // namespace AccessControl
} // namespace Clusters
} // namespace app
} // namespace chip
