/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/TimeSynchronization/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace TimeSynchronization {

inline constexpr uint32_t kRevision = 2;

namespace Attributes {
namespace UTCTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    UTCTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace UTCTime
namespace Granularity{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    Granularity::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace Granularity
namespace TimeSource{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TimeSource::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TimeSource
namespace TrustedTimeSource{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TrustedTimeSource::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TrustedTimeSource
namespace DefaultNTP{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DefaultNTP::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace DefaultNTP
namespace TimeZone{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TimeZone::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TimeZone
namespace DSTOffset{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DSTOffset::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace DSTOffset
namespace LocalTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    LocalTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace LocalTime
namespace TimeZoneDatabase{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TimeZoneDatabase::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TimeZoneDatabase
namespace NTPServerAvailable{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    NTPServerAvailable::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace NTPServerAvailable
namespace TimeZoneListMaxSize{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TimeZoneListMaxSize::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TimeZoneListMaxSize
namespace DSTOffsetListMaxSize{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DSTOffsetListMaxSize::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace DSTOffsetListMaxSize
namespace SupportsDNSResolve{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SupportsDNSResolve::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SupportsDNSResolve

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    UTCTime::kMetadataEntry,
    Granularity::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SetUTCTime {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetUTCTime::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace SetUTCTime
namespace SetTrustedTimeSource {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetTrustedTimeSource::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kAdminister
);
} // namespace SetTrustedTimeSource
namespace SetTimeZone {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetTimeZone::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace SetTimeZone
namespace SetDSTOffset {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetDSTOffset::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace SetDSTOffset
namespace SetDefaultNTP {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetDefaultNTP::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kAdminister
);
} // namespace SetDefaultNTP

} // namespace Commands
} // namespace TimeSynchronization
} // namespace Clusters
} // namespace app
} // namespace chip
