/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <clusters/shared/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace WindowCovering {
namespace Attributes {

// Total number of attributes supported by the cluster, including global attributes
inline constexpr uint32_t kAttributesCount = 27;

namespace Type {
inline constexpr AttributeId Id = 0x00000000;
} // namespace Type


namespace PhysicalClosedLimitLift {
inline constexpr AttributeId Id = 0x00000001;
} // namespace PhysicalClosedLimitLift


namespace PhysicalClosedLimitTilt {
inline constexpr AttributeId Id = 0x00000002;
} // namespace PhysicalClosedLimitTilt


namespace CurrentPositionLift {
inline constexpr AttributeId Id = 0x00000003;
} // namespace CurrentPositionLift


namespace CurrentPositionTilt {
inline constexpr AttributeId Id = 0x00000004;
} // namespace CurrentPositionTilt


namespace NumberOfActuationsLift {
inline constexpr AttributeId Id = 0x00000005;
} // namespace NumberOfActuationsLift


namespace NumberOfActuationsTilt {
inline constexpr AttributeId Id = 0x00000006;
} // namespace NumberOfActuationsTilt


namespace ConfigStatus {
inline constexpr AttributeId Id = 0x00000007;
} // namespace ConfigStatus


namespace CurrentPositionLiftPercentage {
inline constexpr AttributeId Id = 0x00000008;
} // namespace CurrentPositionLiftPercentage


namespace CurrentPositionTiltPercentage {
inline constexpr AttributeId Id = 0x00000009;
} // namespace CurrentPositionTiltPercentage


namespace OperationalStatus {
inline constexpr AttributeId Id = 0x0000000A;
} // namespace OperationalStatus


namespace TargetPositionLiftPercent100ths {
inline constexpr AttributeId Id = 0x0000000B;
} // namespace TargetPositionLiftPercent100ths


namespace TargetPositionTiltPercent100ths {
inline constexpr AttributeId Id = 0x0000000C;
} // namespace TargetPositionTiltPercent100ths


namespace EndProductType {
inline constexpr AttributeId Id = 0x0000000D;
} // namespace EndProductType


namespace CurrentPositionLiftPercent100ths {
inline constexpr AttributeId Id = 0x0000000E;
} // namespace CurrentPositionLiftPercent100ths


namespace CurrentPositionTiltPercent100ths {
inline constexpr AttributeId Id = 0x0000000F;
} // namespace CurrentPositionTiltPercent100ths


namespace InstalledOpenLimitLift {
inline constexpr AttributeId Id = 0x00000010;
} // namespace InstalledOpenLimitLift


namespace InstalledClosedLimitLift {
inline constexpr AttributeId Id = 0x00000011;
} // namespace InstalledClosedLimitLift


namespace InstalledOpenLimitTilt {
inline constexpr AttributeId Id = 0x00000012;
} // namespace InstalledOpenLimitTilt


namespace InstalledClosedLimitTilt {
inline constexpr AttributeId Id = 0x00000013;
} // namespace InstalledClosedLimitTilt


namespace Mode {
inline constexpr AttributeId Id = 0x00000017;
} // namespace Mode


namespace SafetyStatus {
inline constexpr AttributeId Id = 0x0000001A;
} // namespace SafetyStatus


namespace GeneratedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::GeneratedCommandList::Id;
} // namespace GeneratedCommandList


namespace AcceptedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::AcceptedCommandList::Id;
} // namespace AcceptedCommandList


namespace AttributeList {
inline constexpr AttributeId Id = Globals::Attributes::AttributeList::Id;
} // namespace AttributeList


namespace FeatureMap {
inline constexpr AttributeId Id = Globals::Attributes::FeatureMap::Id;
} // namespace FeatureMap


namespace ClusterRevision {
inline constexpr AttributeId Id = Globals::Attributes::ClusterRevision::Id;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace WindowCovering
} // namespace Clusters
} // namespace app
} // namespace chip
