/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace WindowCovering {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 7;


namespace UpOrOpen {
inline constexpr CommandId Id = 0x00000000;
} // namespace UpOrOpen

namespace DownOrClose {
inline constexpr CommandId Id = 0x00000001;
} // namespace DownOrClose

namespace StopMotion {
inline constexpr CommandId Id = 0x00000002;
} // namespace StopMotion

namespace GoToLiftValue {
inline constexpr CommandId Id = 0x00000004;
} // namespace GoToLiftValue

namespace GoToLiftPercentage {
inline constexpr CommandId Id = 0x00000005;
} // namespace GoToLiftPercentage

namespace GoToTiltValue {
inline constexpr CommandId Id = 0x00000007;
} // namespace GoToTiltValue

namespace GoToTiltPercentage {
inline constexpr CommandId Id = 0x00000008;
} // namespace GoToTiltPercentage

} // Commands
} // WindowCovering
} // Clusters
} // app
} // chip
