/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/WebRTCTransportProvider/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace WebRTCTransportProvider {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace CurrentSessions{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentSessions::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kManage,
    std::nullopt
);
} // namespace CurrentSessions

constexpr std::array<DataModel::AttributeEntry, 1> kMandatoryMetadata = {
    CurrentSessions::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SolicitOffer {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SolicitOffer::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace SolicitOffer
namespace ProvideOffer {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ProvideOffer::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace ProvideOffer
namespace ProvideAnswer {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ProvideAnswer::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace ProvideAnswer
namespace ProvideICECandidates {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    ProvideICECandidates::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace ProvideICECandidates
namespace EndSession {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    EndSession::Id,
    BitFlags<DataModel::CommandQualityFlags>(DataModel::CommandQualityFlags::kFabricScoped),
    Access::Privilege::kOperate
);
} // namespace EndSession

} // namespace Commands
} // namespace WebRTCTransportProvider
} // namespace Clusters
} // namespace app
} // namespace chip
