/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/RvcOperationalState/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace RvcOperationalState {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace PhaseList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PhaseList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PhaseList
namespace CurrentPhase{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CurrentPhase::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CurrentPhase
namespace CountdownTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CountdownTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CountdownTime
namespace OperationalStateList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OperationalStateList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OperationalStateList
namespace OperationalState{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OperationalState::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OperationalState
namespace OperationalError{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OperationalError::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OperationalError

constexpr std::array<DataModel::AttributeEntry, 5> kMandatoryMetadata = {
    PhaseList::kMetadataEntry,
    CurrentPhase::kMetadataEntry,
    OperationalStateList::kMetadataEntry,
    OperationalState::kMetadataEntry,
    OperationalError::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace Pause {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Pause::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Pause
namespace Resume {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Resume::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Resume
namespace GoHome {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    GoHome::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace GoHome

} // namespace Commands
} // namespace RvcOperationalState
} // namespace Clusters
} // namespace app
} // namespace chip
