/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/Descriptor/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Descriptor {

inline constexpr uint32_t kRevision = 3;

namespace Attributes {
namespace DeviceTypeList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    DeviceTypeList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace DeviceTypeList
namespace ServerList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ServerList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ServerList
namespace ClientList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ClientList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ClientList
namespace PartsList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PartsList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PartsList
namespace TagList{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    TagList::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace TagList
namespace EndpointUniqueID{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    EndpointUniqueID::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace EndpointUniqueID

constexpr std::array<DataModel::AttributeEntry, 4> kMandatoryMetadata = {
    DeviceTypeList::kMetadataEntry,
    ServerList::kMetadataEntry,
    ClientList::kMetadataEntry,
    PartsList::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {

} // namespace Commands
} // namespace Descriptor
} // namespace Clusters
} // namespace app
} // namespace chip
