/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/PowerTopology/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace PowerTopology {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace AvailableEndpoints{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    AvailableEndpoints::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace AvailableEndpoints
namespace ActiveEndpoints{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ActiveEndpoints::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ActiveEndpoints
namespace ElectricalCircuitNodes{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ElectricalCircuitNodes::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace ElectricalCircuitNodes

constexpr std::array<DataModel::AttributeEntry, 0> kMandatoryMetadata = {
};

} // namespace Attributes

namespace Commands {

} // namespace Commands
} // namespace PowerTopology
} // namespace Clusters
} // namespace app
} // namespace chip
