/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/OnOff/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace OnOff {

inline constexpr uint32_t kRevision = 6;

namespace Attributes {
namespace OnOff{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OnOff::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace OnOff
namespace GlobalSceneControl{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    GlobalSceneControl::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace GlobalSceneControl
namespace OnTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OnTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace OnTime
namespace OffWaitTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    OffWaitTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kOperate
);
} // namespace OffWaitTime
namespace StartUpOnOff{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    StartUpOnOff::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    Access::Privilege::kManage
);
} // namespace StartUpOnOff

constexpr std::array<DataModel::AttributeEntry, 1> kMandatoryMetadata = {
    OnOff::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace Off {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Off::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Off
namespace On {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    On::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace On
namespace Toggle {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    Toggle::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace Toggle
namespace OffWithEffect {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    OffWithEffect::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace OffWithEffect
namespace OnWithRecallGlobalScene {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    OnWithRecallGlobalScene::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace OnWithRecallGlobalScene
namespace OnWithTimedOff {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    OnWithTimedOff::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace OnWithTimedOff

} // namespace Commands
} // namespace OnOff
} // namespace Clusters
} // namespace app
} // namespace chip
