/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/MicrowaveOvenControl/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace MicrowaveOvenControl {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace CookTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    CookTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace CookTime
namespace MaxCookTime{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxCookTime::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxCookTime
namespace PowerSetting{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PowerSetting::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PowerSetting
namespace MinPower{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MinPower::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MinPower
namespace MaxPower{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MaxPower::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MaxPower
namespace PowerStep{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PowerStep::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PowerStep
namespace SupportedWatts{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SupportedWatts::Id,
    BitFlags<DataModel::AttributeQualityFlags>(DataModel::AttributeQualityFlags::kListAttribute),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SupportedWatts
namespace SelectedWattIndex{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SelectedWattIndex::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace SelectedWattIndex
namespace WattRating{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    WattRating::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace WattRating

constexpr std::array<DataModel::AttributeEntry, 2> kMandatoryMetadata = {
    CookTime::kMetadataEntry,
    MaxCookTime::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace SetCookingParameters {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    SetCookingParameters::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace SetCookingParameters
namespace AddMoreTime {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    AddMoreTime::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kOperate
);
} // namespace AddMoreTime

} // namespace Commands
} // namespace MicrowaveOvenControl
} // namespace Clusters
} // namespace app
} // namespace chip
