/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/CommissionerControl/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace CommissionerControl {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace SupportedDeviceCategories{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    SupportedDeviceCategories::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kManage,
    std::nullopt
);
} // namespace SupportedDeviceCategories

constexpr std::array<DataModel::AttributeEntry, 1> kMandatoryMetadata = {
    SupportedDeviceCategories::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {
namespace RequestCommissioningApproval {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    RequestCommissioningApproval::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace RequestCommissioningApproval
namespace CommissionNode {
inline constexpr DataModel::AcceptedCommandEntry kMetadataEntry(
    CommissionNode::Id,
    BitFlags<DataModel::CommandQualityFlags>(),
    Access::Privilege::kManage
);
} // namespace CommissionNode

} // namespace Commands
} // namespace CommissionerControl
} // namespace Clusters
} // namespace app
} // namespace chip
