/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model-provider/MetadataTypes.h>
#include <array>
#include <lib/core/DataModelTypes.h>

#include <cstdint>

#include <clusters/MeterIdentification/Ids.h>

namespace chip {
namespace app {
namespace Clusters {
namespace MeterIdentification {

inline constexpr uint32_t kRevision = 1;

namespace Attributes {
namespace MeterType{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MeterType::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MeterType
namespace PointOfDelivery{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PointOfDelivery::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PointOfDelivery
namespace MeterSerialNumber{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    MeterSerialNumber::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace MeterSerialNumber
namespace ProtocolVersion{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    ProtocolVersion::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace ProtocolVersion
namespace PowerThreshold{
inline constexpr DataModel::AttributeEntry kMetadataEntry(
    PowerThreshold::Id,
    BitFlags<DataModel::AttributeQualityFlags>(),
    Access::Privilege::kView,
    std::nullopt
);
} // namespace PowerThreshold

constexpr std::array<DataModel::AttributeEntry, 3> kMandatoryMetadata = {
    MeterType::kMetadataEntry,
    PointOfDelivery::kMetadataEntry,
    MeterSerialNumber::kMetadataEntry,
};

} // namespace Attributes

namespace Commands {

} // namespace Commands
} // namespace MeterIdentification
} // namespace Clusters
} // namespace app
} // namespace chip
