#!/usr/bin/env bash

# This script generates and builds the SLC project for the given Matter application and board.
#
#   Usage:
#   ./slc/build.sh <slcp/slcw path> <board>
#
#   Example .slcp usage:
#   ./slc/build.sh slc/apps/lighting-app/thread/lighting-app.slcp brd4187c
#       output in: out/brd4187c/lighting-app/
#
#   Example .slcw usage:
#   ./slc/build.sh slc/apps/lighting-app/thread/lighting-app-series-2.slcw brd4187c
#       output in: out/brd4187c/lighting-app-solution/
#
#   Example --configuration option usage:
#   ./slc/build.sh slc/apps/lighting-app/thread/lighting-app.slcp brd4187c --configuration CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:20,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"1.0.0-1.0\"
#       output in: out/brd4187c/lighting-app/
#
#   --skip_gen option : Allows to skip the slc gen step and only run the make commande to rebuild modified files. slc gen normally regenerate your config, autogen, linker_options and makefile for your output folder.
#                       This option only works if the project as previously been generated
#   Example
#   ./slc/build.sh slc/apps/lighting-app/thread/lighting-app.slcp brd4187c --skip_gen
#       output in: out/brd4187c/lighting-app/
#
#   --sisdk option : Allows to build a project using a different SISDK folder, at the provided path, rather than the default one found in third_party/simplicity_sdk
#   Example
#   ./slc/build.sh slc/apps/lighting-app/thread/lighting-app.slcp brd4187c --sisdk /Users/Shared/silabs/Github/sisdk
#       output in: out/brd4187c/lighting-app/
#
#   --with_app option : Allows to specify additional components for the application build for solutions only. If provided for .slcp file, silently ignored.
#   Example
#   ./slc/build.sh slc/sample-app/lighting-app/efr32/lighting-app-thread.slcp brd4187c --with_app '<component1>,<component2>'
#       output in: out/brd4187c/lighting-app-thread/
#
#   --without_app option : Allows to exclude specific components from the application build for solutions only. If provided for .slcp file, silently ignored.
#   Example
#   ./slc/build.sh slc/sample-app/lighting-app/efr32/lighting-app-thread.slcp brd4187c --without_app '<component1>,<component2>'
#       output in: out/brd4187c/lighting-app-thread/
#
#   --with_bootloader option : Allows to specify additional components for the bootloader build for solutions only. If provided for .slcp file, silently ignored.
#   Example
#   ./slc/build.sh slc/solutions/thermostat/series-2/thermostat-917-ncp-bootloader.slcw brd4187c --with_bootloader '<component1>,<component2>'
#       output in: out/brd4187c/thermostat-917-ncp-solution/
#
#   --without_bootloader option : Allows to exclude specific components from the bootloader build for solutions only. If provided for .slcp file, silently ignored.
#   Example
#   ./slc/build.sh slc/solutions/thermostat/series-2/thermostat-917-ncp-bootloader.slcw brd4187c --without_bootloader '<component1>,<component2>'
#       output in: out/brd4187c/thermostat-917-ncp-solution/
#

<<<<<<< HEAD
# Helper functions to build component arguments
build_with_arg() {
	local board="$1"
	local components="$2"

	if [ -n "$components" ]; then
		echo "--with $board,$components"
	else
		echo "--with $board"
	fi
}

build_without_arg() {
	local components="$1"

	if [ -n "$components" ]; then
		echo "--without $components"
	else
		echo ""
	fi
}

# Helper function to run slc generate with retry on timeout
run_slc_generate_with_retry() {
	local max_retries=3
	local attempt=1
	local exit_code=0
	local output=""

	while [ $attempt -le $max_retries ]; do
		echo "Running: slc $* (attempt $attempt/$max_retries)"
		output=$(slc "$@" 2>&1)
		exit_code=$?
		echo "$output"

		if [ $exit_code -eq 0 ]; then
			break
		fi

		# Check for ConcurrentModificationException
		if echo "$output" | grep -q "ConcurrentModificationException: Internal Error. Please see logs."; then
			echo "ConcurrentModificationException detected. Exporting logs..."
			slc --exportLogs=out/artifacts/log
			echo "Logs exported to out/artifacts/log"
			if [ $attempt -lt $max_retries ]; then
				echo "Retrying slc generate command after ConcurrentModificationException..."
				sleep 1
			else
				echo "Maximum retries reached after ConcurrentModificationException."
			fi
		# Check for timeout
		elif echo "$output" | grep -q "Follow-up generation did not complete within.*seconds"; then
			if [ $attempt -lt $max_retries ]; then
				echo "Timeout detected. Retrying slc generate command..."
				sleep 1
			else
				echo "Maximum retries reached after timeout."
			fi
		else
			echo "Attempt $attempt failed with exit code $exit_code (not a timeout or ConcurrentModificationException - no retry)"
			break
		fi

		attempt=$((attempt + 1))
	done
	return $exit_code
}

MATTER_ROOT=$(pwd -P)
: "${GSDK_ROOT:=$MATTER_ROOT/third_party/simplicity_sdk}"

# include env variables from .env file generated by sl_setup_env.py
set -a
if [ -f "$MATTER_ROOT/slc/tools/.env" ]; then
	. "$MATTER_ROOT/slc/tools/.env"
	PATH="$TOOLS_PATH:$PATH"
fi
=======

slt update  --self
make install_app_package
sample_app_path=$(slt where matter_app)
echo "Sample app path: $sample_app_path"

MATTER_ROOT=$(pwd -P)
>>>>>>> 0ee54d848 (This commit combines all the work from implementing package manager)
set +a

echo "cd $sample_app_path"
cd "$sample_app_path"

GSDK_ROOT=$MATTER_ROOT/third_party/simplicity_sdk
SILABS_APP_PATH=$1
SILABS_BOARD=$2
CONFIG_ARGS=""
BRD_ONLY=$(echo $SILABS_BOARD | cut -f1 -d";")
<<<<<<< HEAD
if [ -z "$POST_BUILD_EXE" ]; then
	export POST_BUILD_EXE=$(which commander)
fi

=======
>>>>>>> 0ee54d848 (This commit combines all the work from implementing package manager)
# Determine vars based on project type provided (.slcw solution example or .slcp project example file)
if [[ "$SILABS_APP_PATH" == *.slcw ]]; then
    SILABS_APP=$(basename "$SILABS_APP_PATH" .slcw)
    MAKE_FILE=$SILABS_APP.solution.Makefile
    PROJECT_FLAG="-w"
    OUTPUT_DIR="out/$BRD_ONLY/$SILABS_APP-solution"

elif [[ "$SILABS_APP_PATH" == *.slcp ]]; then
	SILABS_APP=$(basename "$SILABS_APP_PATH" .slcp)
	PROJECT_FLAG="-p"
	OUTPUT_DIR="out/$BRD_ONLY/$SILABS_APP"
	MAKE_FILE=$SILABS_APP.Makefile

else
	echo "Did not provide a valid path for to .slcw or .slcp project file. Returning."
	exit
fi

# remove SILABS_APP_PATH and SILABS_BOARD from list of input args
shift
shift
skip_gen=false
WITH_APP_COMPONENTS=""
WITHOUT_APP_COMPONENTS=""
WITH_BOOTLOADER_COMPONENTS=""
WITHOUT_BOOTLOADER_COMPONENTS=""
while [ $# -gt 0 ]; do
	case "$1" in
	--clean)
		rm -rf $OUTPUT_DIR
		shift
		;;
	--skip_gen)
		skip_gen=true
		shift
		;;
	--sisdk)
		GSDK_ROOT="$2"
		shift
		shift
		;;
	--output_suffix)
		OUTPUT_DIR="${OUTPUT_DIR}-$2"
		shift
		shift
		;;
	--with_app)
		WITH_APP_COMPONENTS="$2"
		shift
		shift
		;;
	--with_app\ *)
		WITH_APP_COMPONENTS="${1#--with_app }"
		shift
		;;
	--without_app)
		WITHOUT_APP_COMPONENTS="$2"
		shift
		shift
		;;
	--without_app\ *)
		WITHOUT_APP_COMPONENTS="${1#--without_app }"
		shift
		;;

	--with_bootloader)
		WITH_BOOTLOADER_COMPONENTS="$2"
		shift
		shift
		;;
	--with_bootloader\ *)
		WITH_BOOTLOADER_COMPONENTS="${1#--with_bootloader }"
		shift
		;;

	--without_bootloader)
		WITHOUT_BOOTLOADER_COMPONENTS="$2"
		shift
		shift
		;;
	--without_bootloader\ *)
		WITHOUT_BOOTLOADER_COMPONENTS="${1#--without_bootloader }"
		shift
		;;

	*)
		CONFIG_ARGS+="$1 "
		shift
		;;
	esac
done
echo $CONFIG_ARGS
<<<<<<< HEAD

# Generate project

if ! [ -x "$(command -v slc)" ]; then
	echo "ERROR: please install slc_cli for your host."
	exit
fi

if ! [ -d "$ARM_GCC_DIR" ]; then
	echo "ERROR: ARM_GCC_DIR is nil."
	exit
fi

if ! [ -d "$ARM_GCC_DIR/bin" ]; then
	echo "ERROR: $ARM_GCC_DIR path should have a bin folder."
	exit
fi

if ! [ -x "$(command -v arm-none-eabi-gcc-12.2.1)" ]; then
	echo "WARNING: might be an incompatible toolchain."
	echo "Please install gcc-arm-none-eabi-12.2.Rel1 for your host."
fi

echo "Building $SILABS_APP for $SILABS_BOARD in $OUTPUT_DIR"

# Ensure Matter repo is registered as SDK extension
[ -d $GSDK_ROOT/extension ] && echo "Directory $GSDK_ROOT/extension exists." || mkdir $GSDK_ROOT/extension

EXTENSION_DIR=$GSDK_ROOT/extension/matter_extension
if [ ! -L "$EXTENSION_DIR" ]; then
	ln -s $MATTER_ROOT "$EXTENSION_DIR"
fi

if [ -z "$WISECONNECT3_DIR" ]; then
	WISECONNECT3_DIR="$GSDK_ROOT/extension/wifi_sdk"
	if [ ! -L "$WISECONNECT3_DIR" ]; then
		ln -s $MATTER_ROOT/third_party/wifi_sdk/ "$WISECONNECT3_DIR"
	fi
=======

# Change to SILABS_APP_PATH directory and run slt install
APP_DIR=$(dirname "$SILABS_APP_PATH")
echo "app ddir = $APP_DIR"
cd "$APP_DIR"
slt install
#verify and print generate pkg.slconf and pkg.lock run and print slt locate matter
# Verify and print generated pkg.slconf and pkg.lock, then run and print 'slt locate matter'
if [ -f autogen/pkg.slconf ]; then
    echo "[INFO] pkg.slconf generated:"
    cat autogen/pkg.slconf
else
    echo "[WARN] pkg.slconf not found!"
fi

if [ -f pkg.lock ]; then
    echo "[INFO] pkg.lock generated:"
    cat pkg.lock
else
    echo "[WARN] pkg.lock not found!"
fi

echo "[INFO] slt locate matter output:"
slt locate matter

# include env variables from .env file generated by sl_setup_env.py
set -a
if [ -f "$MATTER_ROOT/slc/tools/.env" ]; then
    . "$MATTER_ROOT/slc/tools/.env"
    PATH="$TOOLS_PATH:$PATH"
else
    echo "[DEBUG] Locating tool paths..."
    gcc=$(slt locate gcc-arm-none-eabi | grep Path | cut -f 4 -d ' ')
    echo "[DEBUG] gcc-arm-none-eabi path: $gcc"
    gcc_bin=$gcc/bin
    echo "[DEBUG] gcc_bin: $gcc_bin"
    cmake=$(slt locate cmake | grep Path | cut -f 4 -d ' ')/bin
    echo "[DEBUG] cmake path: $cmake"
    iar=$(slt locate iar-embedded-workbench | grep Path | cut -f 4 -d ' ')/arm/bin || echo ""
    echo "[DEBUG] iar path: $iar"
    riscv=$(slt locate gcc-riscv32 | grep Path | cut -f 4 -d ' ')/bin || echo ""
    echo "[DEBUG] riscv path: $riscv"
    slc_path=$(slt locate slc_cli_base | grep Path | cut -f 4 -d ' ') || echo ""
    echo "[DEBUG] slc_cli_base path: $slc_path"

    commander="$(slt where commander)"
    echo "[DEBUG] commander path: $commander"
    export ARM_GCC_DIR="$gcc"
    echo "[DEBUG] Exporting ARM_GCC_DIR=$gcc"

    NEW_PATH="$gcc_bin:$cmake:$slc_path:$commander"
    [ -n "$iar" ] && NEW_PATH="$NEW_PATH:$iar"
    [ -n "$riscv" ] && NEW_PATH="$NEW_PATH:$riscv"
    echo "[DEBUG] Combined NEW_PATH: $NEW_PATH"

    export PATH="$NEW_PATH:$PATH"
    echo "[DEBUG] Exporting PATH=$NEW_PATH:$PATH"
    echo "[DEBUG] which commander : $(which commander)"
    export POST_BUILD_EXE="$(which commander)"
    echo "[DEBUG] Exporting POST_BUILD_EXE=$POST_BUILD_EXE"
fi

if [ -z "$POST_BUILD_EXE" ]; then
    echo "[DEBUG] POST_BUILD_EXE is not set/empty"
    POST_BUILD_EXE=$(which $commander)
    if [ -z "$POST_BUILD_EXE" ]; then
        echo "[ERROR] POST_BUILD_EXE is empty"
        exit 1
    fi
>>>>>>> 0ee54d848 (This commit combines all the work from implementing package manager)
fi
# Generate project

# if ! [ -x "$(command -v slc)" ]; then
#     echo "ERROR: please install slc_cli for your host."
#     exit
# fi

# if ! [ -d "$ARM_GCC_DIR" ]; then
#     echo "ERROR: ARM_GCC_DIR is nil."
#     exit
# fi

# if ! [ -d "$ARM_GCC_DIR/bin" ]; then
#     echo "ERROR: $ARM_GCC_DIR path should have a bin folder."
#     exit
# fi

# if ! [ -x "$(command -v arm-none-eabi-gcc)" ]; then
#     echo "ERROR: $ARM_GCC_DIR/bin missing from PATH"
#     echo "Run export PATH='\$PATH:$ARM_GCC_DIR/bin' to add to PATH"
#     exit
# fi

# if ! [ -x "$(command -v arm-none-eabi-gcc-12.2.1)" ]; then
#     echo "WARNING: might be an incompatible toolchain."
#     echo "Please install gcc-arm-none-eabi-12.2.Rel1 for your host."
# fi

# echo "Building $SILABS_APP for $SILABS_BOARD in $OUTPUT_DIR"

# # Ensure Matter repo is registered as SDK extension
# [ -d $GSDK_ROOT/extension ] && echo "Directory $GSDK_ROOT/extension exists." || mkdir $GSDK_ROOT/extension

# EXTENSION_DIR=$GSDK_ROOT/extension/matter_extension
# if [ ! -L "$EXTENSION_DIR" ]; then
#     ln -s $MATTER_ROOT "$EXTENSION_DIR"
# fi

# WISECONNECT3_DIR=$GSDK_ROOT/extension/wifi_sdk
# if [ ! -L "$WISECONNECT3_DIR" ]; then
#     ln -s $MATTER_ROOT/third_party/wifi_sdk/ "$WISECONNECT3_DIR"
# fi

# ThirdPartyHwDrivers_DIR=third_party/third_party_hw_drivers_extension

# Trust SDK and Matter extension
<<<<<<< HEAD
echo "Ensure SDK and Matter extension are trusted by SLC."
slc configuration --sdk $GSDK_ROOT
slc signature trust --development-trust
slc signature trust --extension-path "$EXTENSION_DIR"
slc signature trust --sdk $GSDK_ROOT --extension-path "$WISECONNECT3_DIR"
slc signature trust --extension-path "$ThirdPartyHwDrivers_DIR"

# Make ZAP available to SLC-CLI
if [ ! -f "$STUDIO_ADAPTER_PACK_PATH/apack.json" ]; then
	export STUDIO_ADAPTER_PACK_PATH=$ZAP_INSTALL_PATH
fi
=======
# echo "Ensure SDK and Matter extension are trusted by SLC."
# slc configuration --sdk $GSDK_ROOT
# slc signature trust --development-trust
# slc signature trust --extension-path "$EXTENSION_DIR"
# slc signature trust --sdk $GSDK_ROOT --extension-path "$WISECONNECT3_DIR"
# slc signature trust --extension-path "$ThirdPartyHwDrivers_DIR"
>>>>>>> 0ee54d848 (This commit combines all the work from implementing package manager)

# # Make ZAP available to SLC-CLI
# if [ ! -f "$STUDIO_ADAPTER_PACK_PATH/apack.json" ]; then
#     export STUDIO_ADAPTER_PACK_PATH=$ZAP_INSTALL_PATH
# fi
echo "cd $sample_app_path"
cd $sample_app_path
echo "pwd: $(pwd)"
if [ "$skip_gen" = false ]; then
<<<<<<< HEAD
	if [[ "$SILABS_APP_PATH" == *.slcw ]]; then
		if [[ "$SILABS_APP_PATH" != *-siwx* ]]; then
			# Get bootloader arguments
			BOOTLOADER_WITH_ARG=$(build_with_arg "$SILABS_BOARD" "$WITH_BOOTLOADER_COMPONENTS")
			BOOTLOADER_WITHOUT_ARG=$(build_without_arg "$WITHOUT_BOOTLOADER_COMPONENTS")

			# Generate bootloader
			echo "Generating bootloader..."
			run_slc_generate_with_retry generate --tt -s $GSDK_ROOT --daemon -d $OUTPUT_DIR $PROJECT_FLAG $SILABS_APP_PATH $BOOTLOADER_WITH_ARG $BOOTLOADER_WITHOUT_ARG -pids bootloader $CONFIG_ARGS --generator-timeout=3500
			if [ $? -ne 0 ]; then
				echo "FAILED TO Generate bootloader for: $SILABS_APP_PATH"
				exit 1
			fi
		fi

		# Get application args
		APP_WITH_ARG=$(build_with_arg "$SILABS_BOARD" "$WITH_APP_COMPONENTS")
		APP_WITHOUT_ARG=$(build_without_arg "$WITHOUT_APP_COMPONENTS")

		echo "Generating application..."
		run_slc_generate_with_retry generate --tt -s $GSDK_ROOT --daemon -d $OUTPUT_DIR $PROJECT_FLAG $SILABS_APP_PATH $APP_WITH_ARG $APP_WITHOUT_ARG -pids application $CONFIG_ARGS --generator-timeout=3500
		if [ $? -ne 0 ]; then
			echo "FAILED TO Generate application for: $SILABS_APP_PATH"
			exit 1
		fi
	else
		# Generate .slcp projects
		run_slc_generate_with_retry generate -d $OUTPUT_DIR $PROJECT_FLAG $SILABS_APP_PATH --with $SILABS_BOARD $CONFIG_ARGS --generator-timeout=3500 -o makefile
		if [ $? -ne 0 ]; then
			echo "FAILED TO Generate : $SILABS_APP_PATH"
			exit 1
		fi
	fi
=======
    echo "[INFO] Generating project files..."
    echo "[INFO] slc generate -d $OUTPUT_DIR $PROJECT_FLAG $SILABS_APP_PATH --with $SILABS_BOARD $CONFIG_ARGS --generator-timeout=2000 -o makefile"
    slc generate -d $OUTPUT_DIR $PROJECT_FLAG $SILABS_APP_PATH --with $SILABS_BOARD $CONFIG_ARGS --generator-timeout=2000 -o makefile
    if [ $? -ne 0 ]; then
        echo "FAILED TO Generate : $SILABS_APP_PATH"
        exit 1
    fi
>>>>>>> 0ee54d848 (This commit combines all the work from implementing package manager)
fi

make all -C $OUTPUT_DIR -f $MAKE_FILE -j13
