/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace EnergyEvse {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 7;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 1;

namespace GetTargetsResponse {
inline constexpr CommandId Id = 0x00000000;
} // namespace GetTargetsResponse

namespace Disable {
inline constexpr CommandId Id = 0x00000001;
} // namespace Disable

namespace EnableCharging {
inline constexpr CommandId Id = 0x00000002;
} // namespace EnableCharging

namespace EnableDischarging {
inline constexpr CommandId Id = 0x00000003;
} // namespace EnableDischarging

namespace StartDiagnostics {
inline constexpr CommandId Id = 0x00000004;
} // namespace StartDiagnostics

namespace SetTargets {
inline constexpr CommandId Id = 0x00000005;
} // namespace SetTargets

namespace GetTargets {
inline constexpr CommandId Id = 0x00000006;
} // namespace GetTargets

namespace ClearTargets {
inline constexpr CommandId Id = 0x00000007;
} // namespace ClearTargets

} // Commands
} // EnergyEvse
} // Clusters
} // app
} // chip
