name: build-linux-tools

on:
    workflow_call:

jobs:
  bootstrap_job:
    uses: SiliconLabsSoftware/matter_build_action/bootstrap@main
    with:
      platform: linux  # Replace 'your-platform-name' with the desired platform name