name: Common Builder

on:
    workflow_call:
        inputs:
            json-file-path:
                required: true
                type: string
            path-to-example-app:
                required: true
                type: string
            example-app:
                required: true
                type: string
            build-type:
                required: true
                type: string
            platform:
                required: true
                type: string

jobs:
    build:
        name: ${{ inputs.platform }}-build-job
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/siliconlabssoftware/matter_extension_dependencies:SiSDKMatter_WiFi_SDKExtension
        steps:
        - name: Checkout repository
          uses: actions/checkout@v5
          with:
            submodules: false
        
        - name: add safe directory
          run: git config --global --add safe.directory /__w/matter_extension/matter_extension

        - name: Verify MATTER_ROOT
          run: |
            if [ ! -d "$MATTER_ROOT" ]; then
                echo "ERROR: Expected MATTER_ROOT directory $MATTER_ROOT missing" >&2; exit 1; fi
                echo "MATTER_ROOT=$MATTER_ROOT"; ls -1 | head -50
                echo "Git HEAD: $(git rev-parse --abbrev-ref HEAD) @ $(git rev-parse --short HEAD)"

        - name: Update submodules
          run: |
            echo "cd to MATTER_ROOT = $MATTER_ROOT"
            cd $MATTER_ROOT
            git submodule update --init

        - name: Install tools
          uses: ./.github/actions/install-tools

        - name: Build ${{ inputs.example-app }}
          uses: SiliconLabsSoftware/matter_build_action@v2
          
          with:
            json-file-path: $MATTER_ROOT/${{ inputs.json-file-path }}
            path-to-example-app: $MATTER_ROOT/${{ inputs.path-to-example-app }}
            example-app: $MATTER_ROOT/${{ inputs.example-app }}
            build-script: "./$MATTER_ROOT/slc/build.sh"
            output-directory: " "
            build-type: ${{ inputs.build-type }}

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ inputs.example-app }}-${{inputs.platform}}-${{ inputs.build-type }}
            path: out/*/*/artifact
            if-no-files-found: warn
            overwrite: true
