name: build-linux-tools

on:
    workflow_call:

jobs:
  bootstrap_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Run bootstrap action
        uses: SiliconLabsSoftware/matter_build_action/bootstrap@main
        with:
          platform: linux