name: build-linux-tools

on:
    workflow_call:

jobs:
  bootstrap_job:
    runs-on: ubuntu-latest
    container:
            image: docker pull ghcr.io/siliconlabssoftware/matter_extension_dependencies:SiSDKv2024.12.1_WiFi_SDKv3.4.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      
      - name: Mark repository as safe for Git
        shell: bash
        run: |
          git config --global --add safe.directory /__w/matter_extension/matter_extension

      - name: Initialize required submodules
        shell: bash
        run: |
          git submodule update --init third_party/matter_sdk
      
      - name: Checkout matter_sdk submodules
        env:
          PW_ENVIRONMENT_ROOT: ${{ github.workspace }}
        shell: bash
        run: |
          cd third_party/matter_sdk
          ./scripts/checkout_submodules.py --platform linux
           echo "PW_ENVIRONMENT_ROOT is set to $PW_ENVIRONMENT_ROOT"
          . scripts/bootstrap.sh
          ./scripts/run_in_build_env.sh "./scripts/build/build_examples.py --target linux-arm64-chip-tool-ipv6only-clang build"
          ./scripts/run_in_build_env.sh "./scripts/build/build_examples.py --target linux-arm64-ota-provider-ipv6only-clang build"
          ./scripts/run_in_build_env.sh "./scripts/build/build_examples.py --target linux-arm64-all-clusters-clang build"
          mkdir -p artifact/Chiptool/linux-arm64-ipv6only-clang
          cp out/linux-arm64-chip-tool-ipv6only-clang/chip-tool artifact/Chiptool/linux-arm64-ipv6only-clang/
          mkdir -p artifact/OTA/linux-arm64-ipv6only-clang
          cp out/linux-arm64-ota-provider-ipv6only-clang/chip-ota-provider-app artifact/OTA/linux-arm64-ipv6only-clang/
          cp out/linux-arm64-all-clusters-clang/chip-all-clusters-app artifact/release/siwx917-rcp-files/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: linux-tools
            path: artifact
            if-no-files-found: error
            overwrite: true

        