name: Common Package Builder

on:
    workflow_call:
        inputs:
            json-file-path:
                required: true
                type: string
            path-to-example-app:
                required: true
                type: string
            example-app:
                required: true
                type: string
            build-type:
                required: true
                type: string
            platform:
                required: true
                type: string
            package-version:
                required: true
                type: string
            conan-cache-key:
                required: true
                type: string

permissions:
  contents: read
  actions: write

jobs:
    build:
        name: ${{ inputs.platform }}-package-build-job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Cache tools
              uses: ./.github/actions/cache-tools

            - name: Restore Matter package cache
              uses: ./.github/actions/restore-matter-packages
              with:
                  conan-cache-key: ${{ inputs.conan-cache-key }}
                  package-version: ${{ inputs.package-version }}
                  fail-on-cache-miss: true

            - name: Build ${{ inputs.example-app }} from packages
              uses: SiliconLabsSoftware/matter_build_action@v2
              continue-on-error: ${{ inputs.build-type == 'custom-sqa' }}
              env:
                  MATTER_PACKAGE_VERSION: ${{ inputs.package-version }}
              with:
                  json-file-path: ${{ inputs.json-file-path }}
                  path-to-example-app: ${{ inputs.path-to-example-app }}
                  example-app: ${{ inputs.example-app }}
                  build-script: "$(slt where matter_app)/build_app.sh"
                  output-directory: " "
                  build-type: ${{ inputs.build-type }}
                  continue-on-error: ${{ inputs.build-type == 'custom-sqa' }}
