name: build-linux-tools

on:
    workflow_call:

jobs:
  bootstrap_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      
      - name: Mark repository as safe for Git
        shell: bash
        run: |
          git config --global --add safe.directory /__w/matter_extension/matter_extension

      - name: Initialize required submodules
        shell: bash
        run: |
          git submodule update --init third_party/matter_sdk
      
      - name: Checkout matter_sdk submodules
        shell: bash
        run: |
          cd third_party/matter_sdk
          ./scripts/checkout_submodules.py --platform linux
          cd ../..

      - name: Run bootstrap action
        uses: SiliconLabsSoftware/matter_build_action/bootstrap@main
        with:
          platform: linux
          
      - name: Set PW_ENVIRONMENT_ROOT environment variable
        env:
          PW_ENVIRONMENT_ROOT: ${{ github.workspace }}
        run: |
          echo "PW_ENVIRONMENT_ROOT is set to $PW_ENVIRONMENT_ROOT"

      - name: Run chip-tool build
        run: |

            cd third_party/matter_sdk
            sh './scripts/run_in_build_env.sh  "./scripts/build/build_examples.py --target linux-arm64-chip-tool-ipv6only-clang build"'
            sh './scripts/run_in_build_env.sh  "./scripts/build/build_examples.py --target linux-arm64-ota-provider-ipv6only-clang build"'
            sh './scripts/run_in_build_env.sh  "./scripts/build/build_examples.py --target linux-arm64-all-clusters-clang build"'
            sh "mkdir -p artifact/Chiptool/linux-arm64-ipv6only-clang; cp out/linux-arm64-chip-tool-ipv6only-clang/chip-tool artifact/Chiptool/linux-arm64-ipv6only-clang/"
            sh "mkdir -p artifact/OTA/linux-arm64-ipv6only-clang; cp out/linux-arm64-ota-provider-ipv6only-clang/chip-ota-provider-app artifact/OTA/linux-arm64-ipv6only-clang/"
            sh "cp out/linux-arm64-all-clusters-clang/chip-all-clusters-app artifact/release/siwx917-rcp-files/"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: linux-tools
            path: artifact
            if-no-files-found: error
            overwrite: true

        