name: Build Zephyr

on:
  push:
    branches:
      - main
      - "release_*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

env:
  CHIP_LOG_TIMESTAMPS: false
  PW_ENVIRONMENT_ROOT: ${{ github.workspace }}/.environment

jobs:
  zephyr-lighting-app:
    name: Lighting App

    runs-on: ubuntu-latest
    if: github.actor != 'restyled-io[bot]'

    container:
      image: ghcr.io/project-chip/chip-build-silabs-zephyr:202
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: false

      - name: Mark repository as safe for Git
        shell: bash
        run: |
          git config --global --add safe.directory '*'

      - name: Initialize matter_sdk submodule
        shell: bash
        run: |
          git submodule update --init third_party/matter_sdk

      - name: Checkout matter_sdk silabs submodules
        shell: bash
        run: |
          cd third_party/matter_sdk
          ./scripts/checkout_submodules.py --shallow --platform silabs_docker

      - name: Bootstrap
        uses: SiliconLabsSoftware/matter_build_action/bootstrap@v2
        with:
          platform: silabs_docker

      - name: Build SiWx917 Zephyr Lighting App
        shell: bash
        run: |
          cd third_party/matter_sdk && ./scripts/run_in_build_env.sh \
             "cd /opt/silabs/zephyr-silabs \
              && west build -b siwx917_rb4338a -p always ${GITHUB_WORKSPACE}/third_party/matter_sdk/examples/lighting-app/silabs/zephyr"

      - name: Export SiWx917 Zephyr RPS
        shell: bash
        run: |
          mkdir -p artifacts
          cp /opt/silabs/zephyr-silabs/build/zephyr/zephyr.rps artifacts/siwx917_rb4338a-zephyr.rps

      - name: Build EFR32xG24 Zephyr Lighting App
        shell: bash
        run: |
          cd third_party/matter_sdk && ./scripts/run_in_build_env.sh \
             "cd /opt/silabs/zephyr-silabs \
              && west build -b xg24_rb4187c -p always ${GITHUB_WORKSPACE}/third_party/matter_sdk/examples/lighting-app/silabs/zephyr"

      - name: Export EFR32xG24 Zephyr HEX
        shell: bash
        run: |
          cp /opt/silabs/zephyr-silabs/build/zephyr/zephyr.hex artifacts/xg24_rb4187c-zephyr.hex

      - name: Upload Zephyr binary artifacts
        uses: actions/upload-artifact@v7
        with:
          name: silabs-zephyr-lighting-app-bin
          path: artifacts/
          if-no-files-found: error
