name: Build Triggers 

on:
  push:
    branches:
# TODO add these lines back       branches:
#            - main
#            - "release_*"
  pull_request:
    branches:
      - main
      - "release_*"
  workflow_dispatch:
    inputs:
      build-type:
        description: "The build type to use"
        required: true
        type: choice
        options:
          - standard
          - full
          - release

concurrency:
  group: build-triggers-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-build-type:
      runs-on: ubuntu-latest
      outputs:
          build-type: ${{ steps.set-build-type.outputs.build-type }}
      steps:
          - name: Set build-type based on event
            id: set-build-type
            run: |
                if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
                    echo "build-type=${{ github.event.inputs.build-type }}" >> $GITHUB_OUTPUT
                elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
                    echo "build-type=standard" >> $GITHUB_OUTPUT
                elif [[ "${{ github.event_name }}" == "push" ]]; then
                    echo "build-type=standard" >> $GITHUB_OUTPUT
                  fi

  call-dev-apps-builder:
    name: Call Dev Apps Builder
    uses: ./.github/workflows/dev-apps-builder.yaml
    with:
      build-type: ${{ needs.set-build-type.outputs.build-type }}

  call-sqa-apps-builder:
    name: Call SQA Apps Builder
    uses: ./.github/workflows/sqa-apps-builder.yaml

  call-sqa-tools-builder:
    name: Call SQA Tools Builder
    uses: ./.github/workflows/sqa-tools-builder.yaml

  merge-apps:
    name: Merge App Artifacts
    runs-on: ubuntu-latest
    needs:
      - call-dev-apps-builder
      - call-sqa-apps-builder
      - call-sqa-tools-builder
      - set-build-type
    if: success()
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: "artifacts"
          delete-merged: true
          pattern: |
            slc-*