name: Merge Dev Artifacts

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string

jobs:
  merge-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: echo build-type
        run: |
            echo "build-type = ${{ inputs.build-type }}"
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Download Sample Apps Artifacts 
        uses: actions/download-artifact@v4
        with:
          name: sample-apps-${{ inputs.build-type }}
          path: sample-apps-${{ inputs.build-type }}

      - name: Merge Artifacts
        run: |
          ls -la
          mkdir -p artifacts
          cp -r sample-apps-${{ inputs.build-type }} artifacts/
          echo "Artifacts merged successfully into artifacts directory."

      - name: Upload Merged Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts