name: publish
on:
  push:
    paths:
      - '.github/workflows/publish.yml'
      - 'Integrations/docker/images/Dockerfile'
jobs:
  publish-efr32-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version variable
        run: echo "VERSION=SiSDKv2024.12.2_WiFi_SDKv3.5.0-FC" >> $GITHUB_ENV
      - name: Build the matter_extension_dependencies Docker image
        run: |
          docker build -f Integrations/docker/images/Dockerfile . --tag ghcr.io/siliconlabssoftware/matter_extension_dependencies:${{ env.VERSION }}
          docker run ghcr.io/siliconlabssoftware/matter_extension_dependencies:${{ env.VERSION }}
          docker push ghcr.io/siliconlabssoftware/matter_extension_dependencies:${{ env.VERSION }}
          