name: Wait for Test Results

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
    secrets:
      private-key:
        required: true

jobs:
  wait-for-jenkins-status:
    name: Wait for Jenkins Status
    runs-on: ubuntu-latest
    steps:
      - name: Determine HEAD SHA
        id: determine_sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            HEAD_SHA="${{ github.sha }}"
          fi
          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_ENV
          echo "Using HEAD_SHA: $HEAD_SHA"

      - name: Create Check Run for Test Results
        id: create_check_run
        uses: ./.github/actions/create-check-run
        with:
          app-id: ${{ vars.SILABSSW_MATTER_CI_BOT_APP_ID }}
          private-key: ${{ secrets.private-key }}
          repository: ${{ github.repository }}
          check-name: "Wait for Test Results"
          head-sha: ${{ env.HEAD_SHA }}

      - name: Wait for Test Results (with token refresh)
        uses: ./.github/actions/wait-for-check-run
        with:
          app-id: ${{ vars.SILABSSW_MATTER_CI_BOT_APP_ID }}
          private-key: ${{ secrets.private-key }}
          repository: ${{ github.repository }}
          check-run-id: ${{ steps.create_check_run.outputs.check-run-id }}
          poll-interval: 60
          window-seconds: 3600
          max-windows: 10