name: Build SQA apps

on:
    push:

concurrency:
    group: sqa-build-examples-${{github.ref}}
    cancel-in-progress: false

jobs:
    build-lighting-app:
        name: Build Lighting App
        uses: ./.github/workflows/platform-builder.yaml
        with:
            example-app: "lighting-app"
            build-type: "custom-sqa"

    build-lock-app:
        name: Build Lock App
        uses: ./.github/workflows/platform-builder.yaml
        with:
            example-app: "lock-app"
            build-type: "custom-sqa"
            ncp-917-support: true
            ncp-wf200-support: true
            ncp-rs911x-support: true

    build-light-switch-app:
        name: Build Light Switch App
        uses: ./.github/workflows/platform-builder.yaml
        with:
            example-app: "light-switch-app"
            build-type: "custom-sqa"

    build-multi-sensor-app:
        name: Build Multi Sensor App
        uses: ./.github/workflows/platform-builder.yaml
        with:
            example-app: "multi-sensor-app"
            build-type: "custom-sqa"

    build-window-app:
        name: Build Window App
        uses: ./.github/workflows/platform-builder.yaml
        with:
            example-app: "window-app"
            build-type: "custom-sqa"
            ncp-917-support: true

    build-dishwasher-app:
        name: Build Dishwasher App
        uses: ./.github/workflows/platform-builder.yaml
        with:
            example-app: "dishwasher-app"
            build-type: "custom-sqa"

    build-thermostat-app:
        name: Build Thermostat App
        uses: ./.github/workflows/platform-builder.yaml
        with:
            example-app: "thermostat"
            build-type: "custom-sqa"
            ncp-917-support: true
            ncp-wf200-support: true
            ncp-rs911x-support: true

    build-zigbee-matter-light-app:
        name: Build Zigbee Matter Light App
        uses: ./.github/workflows/platform-builder.yaml
        with:
            example-app: "zigbee-matter-light"
            build-type: "custom-sqa"
            thread-keyword: ""
            mg24-internal-support: false
            mgm24-support: false
            mgm24-internal-support: false
            ncp-917-support: false
            ncp-wf200-support: false
            ncp-rs911x-support: false
            wifi-soc-support: false

    merge-apps:
        name: Merge App Artifacts
        runs-on: ubuntu-latest
        needs:
            - build-lighting-app
            - build-lock-app
            - build-light-switch-app
            - build-multi-sensor-app
            - build-window-app
            - build-dishwasher-app
            - build-thermostat-app
            - build-zigbee-matter-light-app
        if: success()

        steps:
            - name: Merge artifacts
              uses: actions/upload-artifact/merge@v4
              with:
                  name: "sqa-artifacts"
                  delete-merged: true
                  pattern: "*-custom-sqa"