name: Validate Gitmodules Branches

on:
  push:
    branches:
      - main
      - "release_*"
  pull_request:
    branches:
      - main
      - "release_*"

concurrency:
  group: validate-gitmodules-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-gitmodules-branches:
    uses: SiliconLabsSoftware/matter_build_action/.github/workflows/validate-gitmodules-branches.yaml@shared_gitmodules_action # TODO: update to tagged version after testing
    with:
      submodules: |
        third_party/matter_sdk
        third_party/matter_support