name: Validate Gitmodules Branches

on:
  push:
    branches:
      - main
      - "release_*"
      - gitmodules_workflow_2.10 #TODO: remove this branch after testing
  pull_request:
    branches:
      - main
      - "release_*"

concurrency:
  group: validate-gitmodules-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-gitmodules-branches:
    name: Validate submodule branch entries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: false

      - name: Validate Gitmodules Branches
        uses: SiliconLabsSoftware/action-gitmodule-validation@main #TODO: update to tagged version after testing
        with:
          submodules: third_party/matter_sdk third_party/matter_support