/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <clusters/shared/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace OperationalCredentials {
namespace Attributes {

// Total number of attributes supported by the cluster, including global attributes
inline constexpr uint32_t kAttributesCount = 11;

namespace NOCs {
inline constexpr AttributeId Id = 0x00000000;
} // namespace NOCs


namespace Fabrics {
inline constexpr AttributeId Id = 0x00000001;
} // namespace Fabrics


namespace SupportedFabrics {
inline constexpr AttributeId Id = 0x00000002;
} // namespace SupportedFabrics


namespace CommissionedFabrics {
inline constexpr AttributeId Id = 0x00000003;
} // namespace CommissionedFabrics


namespace TrustedRootCertificates {
inline constexpr AttributeId Id = 0x00000004;
} // namespace TrustedRootCertificates


namespace CurrentFabricIndex {
inline constexpr AttributeId Id = 0x00000005;
} // namespace CurrentFabricIndex


namespace GeneratedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::GeneratedCommandList::Id;
} // namespace GeneratedCommandList


namespace AcceptedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::AcceptedCommandList::Id;
} // namespace AcceptedCommandList


namespace AttributeList {
inline constexpr AttributeId Id = Globals::Attributes::AttributeList::Id;
} // namespace AttributeList


namespace FeatureMap {
inline constexpr AttributeId Id = Globals::Attributes::FeatureMap::Id;
} // namespace FeatureMap


namespace ClusterRevision {
inline constexpr AttributeId Id = Globals::Attributes::ClusterRevision::Id;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace OperationalCredentials
} // namespace Clusters
} // namespace app
} // namespace chip
