/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace OperationalCredentials {
namespace Commands {

// Total number of client to server commands supported by the cluster
inline constexpr uint32_t kAcceptedCommandsCount = 10;

// Total number of server to client commands supported by the cluster (response commands)
inline constexpr uint32_t kGeneratedCommandsCount = 5;

namespace AttestationRequest {
inline constexpr CommandId Id = 0x00000000;
} // namespace AttestationRequest

namespace AttestationResponse {
inline constexpr CommandId Id = 0x00000001;
} // namespace AttestationResponse

namespace CertificateChainRequest {
inline constexpr CommandId Id = 0x00000002;
} // namespace CertificateChainRequest

namespace CertificateChainResponse {
inline constexpr CommandId Id = 0x00000003;
} // namespace CertificateChainResponse

namespace CSRRequest {
inline constexpr CommandId Id = 0x00000004;
} // namespace CSRRequest

namespace CSRResponse {
inline constexpr CommandId Id = 0x00000005;
} // namespace CSRResponse

namespace AddNOC {
inline constexpr CommandId Id = 0x00000006;
} // namespace AddNOC

namespace UpdateNOC {
inline constexpr CommandId Id = 0x00000007;
} // namespace UpdateNOC

namespace NOCResponse {
inline constexpr CommandId Id = 0x00000008;
} // namespace NOCResponse

namespace UpdateFabricLabel {
inline constexpr CommandId Id = 0x00000009;
} // namespace UpdateFabricLabel

namespace RemoveFabric {
inline constexpr CommandId Id = 0x0000000A;
} // namespace RemoveFabric

namespace AddTrustedRootCertificate {
inline constexpr CommandId Id = 0x0000000B;
} // namespace AddTrustedRootCertificate

namespace SetVIDVerificationStatement {
inline constexpr CommandId Id = 0x0000000C;
} // namespace SetVIDVerificationStatement

namespace SignVIDVerificationRequest {
inline constexpr CommandId Id = 0x0000000D;
} // namespace SignVIDVerificationRequest

namespace SignVIDVerificationResponse {
inline constexpr CommandId Id = 0x0000000E;
} // namespace SignVIDVerificationResponse

} // Commands
} // OperationalCredentials
} // Clusters
} // app
} // chip
